apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/pvc.yaml
  - manifests/config.sops.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/backup-secret.sops.yaml
  - manifests/backup-cronjob.yaml
