apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: openebs-io-engine
  namespace: openebs
spec:
  selector:
    matchLabels:
      app: metrics-exporter-io-engine
  namespaceSelector:
    matchNames:
      - openebs
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
