apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/cf-api-key.sops.yaml
  - manifests/pvc.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/service-tailscale.yaml
