apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/redis-cache.yaml
  - manifests/configmap.yaml
  - manifests/daemonset.yaml
  - manifests/services.yaml
  - manifests/service-monitor.yaml
  - manifests/blocky-db-uri.sops.yaml
  - manifests/blocky-db-credentials.sops.yaml
  - manifests/grafana-dashboard.yaml
  - manifests/grafana-datasource.yaml
