apiVersion: v1
kind: Secret
metadata:
  name: gitlab-root-password
  namespace: devtools
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:C0D4XQaKCL1KUraL2MnWMfr5cDHyNllYXpNWvA==,iv:tEgEDT7DMh+W302eNVQ5S8f1Wa8xRiseBhoiXP54jCY=,tag:ajTwMPfR98uv1aii6wZecQ==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVHV0OGxhTmJJMkwreFJl
        M3JyaEdBT1g1c09FbDZpM0gxMU9nQ3lJQW5NCjVMQ1dWTWZkdllOTC9kZ0JnUVo5
        d2hCVXN3L0g3RWEybjlnMFM2alh3VncKLS0tIGYvVjZmQTVKeUQwdGhzTXFHZ2pV
        dEVsR3FtYVNadHNuYzVhRzNpZ3pRQW8K5Plh2zkN1RsomPs8LXq0zguQbOG/axFI
        hk0SY06xe+UZWyBq019MQwgGA+jwWlqUI4lyEGN4lQnQ8T7X3QrS6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-10T19:18:51Z"
  mac: ENC[AES256_GCM,data:TT2YHZ+tC+DsWwTnlvaMoKmnqfAiCIsSt/H9ipDs6jzWjLlflj4p+LgAbpKcUmRto3P7klElFlJRid3xBHGF1de2IBtkzhRwQu8y+5HMq+U4fQsC7nPwKfzCs1Hb9lQ7u/O1carLW9sPsY7DnNRUqCWWvaVxEJ2G5aY45wSaSe4=,iv:0F4Ekr6uuFtNBBKkU6TMblzMbq4dTxyyiqU3lpAdmQ4=,tag:F3NwQFnyUj/ue7a1I4WaxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
