apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cluster-nvmf
parameters:
  allowVolumeExpansion: "true"
  fsType: xfs
  protocol: nvmf
  repl: "3"
provisioner: io.openebs.csi-mayastor
