apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # cert-manager
  - cert-manager/test-issuer.yaml
  - cert-manager/prod-issuer.yaml

  # cilium (hubble UI)
  - cilium/hubble-oidc.sops.yaml
  - cilium/hubble-route.yaml
  - cilium/hubble-security-policy.yaml
  - cilium/service-monitor.yaml
  - cilium/grafana-dashboard.yaml

  # cloudnative-pg
  - cloudnative-pg/cluster.yaml
  - cloudnative-pg/blocky-database.yaml
  - cloudnative-pg/forgejo-database.yaml
  - cloudnative-pg/grafana-database.yaml
  - cloudnative-pg/wasabi-credentials.sops.yaml
  - cloudnative-pg/scheduled-backup.yaml
  - cloudnative-pg/pod-monitor.yaml

  # metallb
  - metallb/omada-pool.yaml
  - metallb/blocky-pool.yaml
  - metallb/samba-pool.yaml

  # envoy
  - envoy/metallb.yaml
  - envoy/gateway-class.yaml
  - envoy/gateway.yaml
  - envoy/gateway-grant.yaml
  - envoy/fallback-page.yaml
  - envoy/service-monitor.yaml
  - envoy/grafana-dashboard.yaml

  # flux-operator
  - flux-operator/instance.yaml

  # openebs
  - openebs/disk-pools.yaml
  - openebs/storage-class.yaml
  - openebs/service-monitor.yaml
