apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: Ya5IdPv9UmGdCPr269K3aLQ2JwDQlp0KtEmDV1OB
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: aarnavtale@icloud.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: aarnavtale@icloud.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
