apiVersion: v1
kind: ConfigMap
metadata:
  name: gickup-config
  namespace: devtools
data:
  conf.yml: |
    source:
      github:
        - token: GICKUP_GITHUB_TOKEN
          includeorgs:
            - tale
            - chariz
            - sileo
            - zbrateam
            - cnstr
            - codegrounds
            - repostandards
            - aemulo
            - aet-vthacks
            - ghostty-org
          starred: false
          wiki: false
          filter:
            excludeforks: true
            excludearchived: true
    destination:
      gitea:
        - url: http://forgejo-http.devtools.svc.cluster.local:3000
          token_file: /run/gickup/forgejo-token
          createorg: true
          lfs: true
          visibility:
            repositories: public
            organizations: public
