apiVersion: v1
kind: Secret
metadata:
  name: gickup-secrets
  namespace: devtools
type: Opaque
stringData:
  github-token: ENC[AES256_GCM,data:ROiCH+QUjNe8zqy+a9Xwse2sjE6FSJhvjAWOdq41zkkdhmGaQmxkbg==,iv:Waw5GAu+rWtZhzzAMhwsuLsEp7tM8zSwYXfH4TIhjDg=,tag:lMyj0zjsORtXkfj8oEt0GA==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSm5FN0JYMWY3a3JBcnAz
        d2Jid3RDU09DaEUvSFc2UWFrQTNGb1lZOWtrCkY0c0FoNWNyOFQ3T3dCdVhqSVZk
        OW93K1VoM0tHMnBXeFhOTkZ0SFB1bTgKLS0tIHl3WWNIbjJhSnp0V1E1aCsyTjdE
        TUhJcWdZa1lKRVlMODEvU2YwaXZrNjAKtxz49FS6n1tSKWDr4FnzoVBfsNk1qUOg
        CIQ3XfkY5HgaQRhu5yRm6zW80MZx1WK1UUGqv+6CHrBRtWKVzLXJ1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-04T18:42:04Z"
  mac: ENC[AES256_GCM,data:wQQ/4/mEF2EXJzNvXzsZuhJ1mRxhCZ3tLK4v+tsE/MIi0D47YTExQuWWETpbBR4F9meDdp7D9kI2VmwqjvAeby1sZGAZamt8uD4jxKJ0fgPLQWINBxsytJBMYP8x/go734H3K6MrJXkrr99UTR1j5zH9TJREpDciCS11+8IuQ7A=,iv:cuvRwK83ocsrVysu8LGOEq9HEeHcU9WWZcRj5pG9C14=,tag:yIUA1eJIW35P0WjNGimOSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
