[tools]
"ubi:siderolabs/talos" = "1.10.6"
"aqua:helm/helm" = "3.18.4"
"aqua:getsops/sops" = "3.10.2"
"aqua:FiloSottile/age" = "1.2.1"
"ubi:casey/just" = "1.42.4"

[env]
SOPS_AGE_KEY_FILE = "{{env.HOME}}/.config/sops/age/keys.txt"

[tasks.talos-gen]
alias = ['tg']
description = 'Generate a talos configuration with the correct patches'
run = """
talos mc patch talos/controlplane.yaml \
	--patch @talos/patches/tailscale.yaml \
	--patch @talos/patches/{{arg(name="node")}}.yaml \
	-o gen/{{arg(name="node")}}.yaml
"""
