[tools]
"github:siderolabs/talos" = "1.13.7"
"aqua:helm/helm" = "4.2.3"
"aqua:getsops/sops" = "3.10.2"
"aqua:FiloSottile/age" = "1.2.1"
"npm:oxfmt" = "latest"
flux2 = "latest"
lefthook = "latest"
"aqua:mikefarah/yq" = "latest"
"github:budimanjojo/talhelper" = "3.1.15"

[hooks]
postinstall = "lefthook install"

[env]
SOPS_AGE_KEY_FILE = "{{env.HOME}}/.config/sops/age/keys.txt"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
