apiVersion: v1
kind: Secret
metadata:
  name: capacitor-oidc-secret
  namespace: flux-system
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:7AEcfwf4q3jTXRBp/SJDHRg0Grpn85+7cZiz0cSi1lE=,iv:Q1aeyZqRWS/zK39mA3PHNS86LBAEakGgc6FKJsRgUdQ=,tag:rKqWujZTre5QhaXLJu5eYA==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RTRDeUZHbmVyYW5QTmVV
        VVZON3U3SE52cFM1UWZmY2tlTXFSKzBCMkVNCktMYVk1b1owWTR5U01QaWdKSTMr
        K21lV2p3L3dzQVVlbFRrS2VCRzhqMFUKLS0tIGtmeWNzZ3p6MkJGRDJtQXFDL3Vj
        NHI0TjNrSzg4VC9tUzhGN21aOW8zNmsKACq+yTwXKDX8VnYipwEcejdMOJFIc4Tz
        VAUYLq6oY5oGpnPdVbzvSay2w6tA8qR+hVSatP5wBVr6Nt0tiY/HKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T03:36:31Z"
  mac: ENC[AES256_GCM,data:rkbltSZ1K3m2vVr52EgoeCaO/pvKCBS9mwGCHe+5pLDQXS6pdjMmSk9+wKSkAeM4eh58IDXOl44QkvTOATIN63obylCEEomCVK56SCuxMF6OHklD895ay6DgsDvlhiCsX6EA3tSyEr+2eM/9rPt3W08U87hcKGXoCGBD1Ph2duw=,iv:5wpg4MRjiR4A6IGbG16VT3HVIjQcQUtmxF1ph5VLwGk=,tag:FVa5qIQLvxvc4alyzftOgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
