apiVersion: v1
kind: Secret
metadata:
  name: authentik-oidc-secrets
  namespace: authentik
type: Opaque
stringData:
  flux: ENC[AES256_GCM,data:m21NdxhAKXVJpJISYF+Nh2NahX6vfNZTryd8S6y+xaCyFfGBLeUZnb26R+VRjv4dmdK5hKrCOczU41oxsxVK2w6v7c1gxp+SkBRmbRN/EJMrBJ7gMtTFS9WtUkhdqXoG5W7eIpAVwhjMBZwYCXwCJzPa/Jhb3AiddXy+a2p+uOM=,iv:NEn13VxL0OhD4KSUFWVnzdvZqQsIcx1Fim2qeNMmQyI=,tag:4GQSb8Fqzng78DEFv9qYzg==,type:str]
  forgejo: ENC[AES256_GCM,data:/+PO8lOu0XGvkdEYTFeXfX0EdDc+tm+mxSJpAuhfOHozJtQXSfNjeCg1eJ8Y+mqQ6I2twyI9pSzee2MnM+J2WzLuZje49Oq3aJQcU34nKqxz7SNJPr6/b5dBerpBEH5pEjCiP1aYyEloXr7BB4U9FeLdVLaBuNkpaPydhzaCqBk=,iv:JsjDupKDjwNUuike2AJPAAjjeOZPvuArARh6HOIjR1o=,tag:S3u+SmAWIOkAzGoStnDyyg==,type:str]
  grafana: ENC[AES256_GCM,data:Pl9OWHH8A/vKe1l5VW4uq+yon3qdiHdjHm61JtvFhYz70o7/Pvd0mpjVFBbQPol9eJEUVHQUIEYbI7+4CQW7hVNb8K/LQOoMfRz9/TiI8UP+ptsFT2JV8qkgVD49SugIdKHIsSau32QjPyfU8uolDdmQPSxnEgeRwAJCezGQVOg=,iv:90AWoav6Rq/FEmkj/LD2ezvFTK1b99Heu5F2HMgV5G4=,tag:+LymcQgNKFeDOYeJ4RpofQ==,type:str]
  wakapi: ENC[AES256_GCM,data:GtvIw8VbJjKy05gNWcu0ydPmn/tS2B2IRHMdQ9+UsWjLQPH4//uSFvi2onC6ejbLSyaZjAQ6PEyj+/mlLHkQLsnHhUiXXrCCtuQ2m9vCSz1qE1JV2nmQ3SG3GZyjNfArQyMb4xEXIfyYhKv+mlUFjZ/SPVuTQdKTs4NUPSq+sho=,iv:t8CafajbMO9rHO4KEcOTR+larzn6bALoAYdx2GnHSA0=,tag:k01e2FbVsbOz/zr0tFwOSA==,type:str]
  headplane: ENC[AES256_GCM,data:Q+2N/y3C0zlHjfW0Tmyy2CUCisU9eHBurc5dvEuyF8mvHdDKgDeC37B3voLnwBDkXk3hWu3SZcJldB2x7mxKfxvierN1AqookHEyXC4gmWFyfzHwvhAK+VtrwnNScZnpUXsvYK+maciVwpXjDY/VBBocqDFOG0hykK5Nqpjjc2s=,iv:4EcSd3+2xp2oMhII1mpdJvCAs6CXWcFEyobzSPDWXTU=,tag:oq579lC0C/Dcp7yXyqTfjw==,type:str]
  home-assistant: ENC[AES256_GCM,data:bkATdiCoQdZ22R3EqKr3tsNUaRHegf1oPFdr3ztaQcg9jsY0096c/5wFdqA7Hjx/2kUIqxEJj1goLa66pQ20DdxBoIpYe9nQfClxq5n+eB4jW8+wQHvWMMtlQ0ScoXzeJpdwhHN4yVdTA6ZuYC7KJfe3/elumkxh6wgnSqhqaMA=,iv:V9llKyppeWgjVe6k7ZXfgqFPQQ6h3APyAlhomF4Kup4=,tag:R7JtItanuSbTu/gf9vXiDQ==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb0UrZ3Mzb29JMGZjQ1V2
        bmJoQXhqVTBVb3JGTFIraWpMZEZxOXl6RkZVClJvMmRlcUNlbmlScDhtNE5FL3c5
        MEdzaGRzSmhleW1lcXRsTlBuRzl4N2cKLS0tIDdBRFNQeTkyK3FJTDl0YVlLZHdt
        TkdrNytPZXJKL2ozNXdjOTNWejF4WDgKTTmvbBphffsyDzuwYiGArxVCgRCa5Zwe
        J9QsNjCN9A1FpcrS48IIyutaepo1eaovhn4to4EmIpngHcE2sB05Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-28T02:47:28Z"
  mac: ENC[AES256_GCM,data:ydcwyaFenBhRc3rSmi0CrN/VfMbc/xMhjjuwHpwH3oUoA53MQ9u83bUFQDJlc/KtCOt/8nlCYb50iNM6tDnGaMfYTcZ+g+a9I9bpa8+yY4UfDgyvjXSw0u0zgahxj9B20+6p0CLqoo32rn3FKGKY+6XRJlbLF8gxDWIvx7KWVGs=,iv:+NIZ7UTiXbIK0FtbYtJLW4EPaVjuPVwIIbelUdzKdus=,tag:Djvc5M1M08BceZ1R7jTs9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
