apiVersion: v1
kind: Secret
metadata:
  name: authentik-oidc-secrets
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_OIDC_SECRET_FLUX: ENC[AES256_GCM,data:FXTUCxO58MCsGE11OW9N7LmcwWU0fJTYzrjzr2Tcs/ai2xTGC0i2IOhaZ6JL3jwPcDtB42+qsiMLMz5U2ayIIpv/rkMJdCH6V9KSa+TmN0Rjm3Ex63Vhc4vIgKOqs/ulL2k/ZfdOtzy270bD1BLb+rve34UTwZA14eTPSZuvhdY=,iv:zCjaPQbTBJbEFuwsTbfttyNq3Plxy1VjPBKYYXSxpow=,tag:ASLXAhUFBBXwyLPW8JFySg==,type:str]
  AUTHENTIK_OIDC_SECRET_FORGEJO: ENC[AES256_GCM,data:kOWjGhuA5bEODxetL5ZtAOyHxsD+yta3nt39Zj2HCpg/zaVKRx7BT+BYtoczT7KBy8hIihoPTpNvXOxPxTjnIEwG0SdE9+yEDT9J1NsjUYeee50coGYS4gxQ7HPKkSZCNzfBVMUL4P2Ou6a1byadesTzKGwYbXifMCbrYENBn4g=,iv:ADO82r8mAxmxI9xrClP+EvKAP6a5Y77yYZAlZORb3ic=,tag:JTBPcqhhyWkrp2QYAWZvAg==,type:str]
  AUTHENTIK_OIDC_SECRET_GRAFANA: ENC[AES256_GCM,data:VeszCEi7O6Iey4TKD5jSu8bYmDTxWivGmyne7Dguv3efu4cerjOebZC0zuqb3aJnef/T3cUkujiwkCQKGjRMvHW0tbmon7gVBnefw3zcbPIlE3F7Jd1nQ48UM2SklThAY5GdmnLBZs86mfnAXQF7jW0mWAbc6R9nWQ8r3f7bTDI=,iv:JjTDLEoVWxeXzWtKW+NCzkgWkSVIQacxp7v8lL8Lyio=,tag:f9JPV7CLODi/9zANO/O6Ng==,type:str]
  AUTHENTIK_OIDC_SECRET_WAKAPI: ENC[AES256_GCM,data:9WxRoJvMNvkepJ0KKaSjV1bwxGusGoRL/QkzJktS4W3BQmuVgJa90KtnCIS2vbnmh7tG1rzOGx3Cg7VZZjnncK5qknAScNcYxSXMvo2o13p1mkk7o4abA8KohfqANoiEut6YqDzN6EXPF6F7mdAwpO1f7ERjelP3r7LtmFJjhn8=,iv:Pu0vDF4XK3sGbe3fitypGbYuQMnJj2V/9E3ayj3fazc=,tag:m5X2kjQ9TvyDV9vwi0pDTQ==,type:str]
  AUTHENTIK_OIDC_SECRET_HEADPLANE: ENC[AES256_GCM,data:DEJunchbO8laYm1XCjDeyszqukzCmgWMBEo1QQwLscDEP/YUV8rqsLeGvHFYZa43c/j/DiOWSFgTq6o6iAIhbE8yjl58txqMb2ydR8wpm6xnWv7TMZs5TaO20RkGXwvvxpuDpGvdXT5njSRxjCttUIXH7MBs44fePfGpbE9vWEc=,iv:64CDoH5go1fzETl9D9j/WECOpzyPCXz6WpBTS4TqYfM=,tag:jEDgzBjzwrZAIsVHGNV3eA==,type:str]
  AUTHENTIK_OIDC_SECRET_HOME_ASSISTANT: ENC[AES256_GCM,data:YE5J9LhzTXzhORxnBib+70H/XubWKu9mAZF99IgMb1KKM814nbfxLLxFfRobWD5H0O6Gjz9N41C0D9+sk571TdlIoi0L5kGnnCrU36F2zjgzrx6rZvCog4GyloOZjPYTqrSXa8fKwU3jFTjDrpQRUvrTyZ32dCMdFHk7YzamQUU=,iv:xzFU2m+bUkLVA0LYG/PTWhwnZsmLZfDSsRi+h16UsGg=,tag:CuNRbx6uJMrvG330PT/7zw==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQ3pTY0M2UmlvQmQydzZE
        YVI3MHROVTA4eUYzVGNYdWtFZ1dBOVFNMURzCnZtb1ByN0VjUjY2RHF3djZqRWo2
        b3hhMTdoU3M4d2hmazV0OUJVRGZjNU0KLS0tIHkveXVoRk5wdmh1a0hqeC90c2JC
        MEdVZkVoMTNXQzJLakJLT202WkxYa28KMu4JIwmwJsSuUYd022m+GKy0TpoDxJi+
        4iup9c8jatfZkqxZiGv3nX8UOnOB7CP35eeDBU/VdAU6SNfCg6dHRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-04T19:34:37Z"
  mac: ENC[AES256_GCM,data:JGKuQ2N+zQlrkQn/4XUYm8jRQXuNgnPsyNYBaZv/sDgXfSA+8fiOSpV8YTd/bd8WS16lwhUPmdwdkQ7iXurqzCVLtwVabbjfJEwZ26FmN72c7gXuq2+ojsNCg1FNzxmVu4G37seZ0igubqtUBc9rGOiMWQBrSwAoFYD5ff5FrF0=,iv:xoUBICLXo/yLWjNIsR9ZM5fR3ejddzIXpSENfwSVV9M=,tag:qXAPhVEj0Qllz4IJGI75LA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
