apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
stringData:
  secret-key: ENC[AES256_GCM,data:P8utlpJfiHbcKIg5U6e/XuTaUoRdmUnYPXKW9x7gwGVLlBpXzpbDLCFCJjT7j+GGxZQDFyd/mDRiS5fDfEhF9Q==,iv:M2nhoTYzZ0BMos3znpE2JY3KNmdKZ/aAkYEgo+qKj5U=,tag:Brss5ICDenQgWARdq4sy5Q==,type:str]
  db-password: ENC[AES256_GCM,data:HD9HcNUiPBYGZ9/35qzG+SGouwiyre39MrkX5dVoGGpc6yXQvOPBMTlrwpnWjIaf4fW0ghI+LEeSp1luQupoWQ==,iv:6qk133ZuepSjuuBI15CsdkHE0YZc7qy49uKT06QTI7U=,tag:ijAaT94NUidCh5tcrWdfDw==,type:str]
  ses-username: ENC[AES256_GCM,data:POBQC2Oc3ERIcrR8AJfIwXA2alk=,iv:z4K6EHyR2EfTU3Pt7frvGEn9yWkSEMu59RZcZv8zgNE=,tag:RhSik4zKAKG4DBMLMk2A3A==,type:str]
  ses-password: ENC[AES256_GCM,data:pVLx2prLWf7kXV+AvDIkNbXCEstxUMP/nQ7Qn9M48xbigcHNNARs4eu4AP8=,iv:b5Ww9mrglqqeLWKIYepvHzuCmHuq7IvTZRTL9rZsgoM=,tag:AEjeLZ7TWxjZEcaQdAFUzg==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaVhsSnYwUTA5WThXNWhJ
        bnNPeXd2azYwVmpja1FjWCtxUWh2L2JHQWpzClAxdS9McFZ6UHdGcGphaU4yNm1t
        aENjN1BxcENEN2dmUFJlVUhXNVo3QkEKLS0tIHFYcjdBdVM0WDVhVGpkSXp6NWZv
        OFVCNEJURy9ZMkQwSUZPWGU3NXoza3cK/N2RI3t90QE61AfeyyLICsX9d9Y1Rn7o
        0qUmUTHAbc8F8flCuOVp+yMHk5fEoE5OG386522Ku67/DVKqVK61nA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T18:11:19Z"
  mac: ENC[AES256_GCM,data:0O2oMV8VqJSTzZqJfyDDObvlYGWZYwCC3pMHQhRtzmJsAK+7w2E752Qf1MPmn2xwxxLM+T2nKBHLVoLUbeF7gh0Mf4o2PXhlt5MAAAvGcbmh7FHWi3ROfgBBwIU8JaQbRIF016DLymWOZku6zXIaJEaVIf8aLKYDb/g2z+f43Qk=,iv:gnweuVZ0PiW2CnFUXo6rLQV7QgkOQtiX6rsYgBOba0I=,tag:yy8LWYkdtDjF1XpmXMpfWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
