apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app: me.tale.cloudflare-ddns
  template:
    metadata:
      labels:
        app: me.tale.cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: timothyjmiller/cloudflare-ddns:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              memory: "32Mi"
              cpu: "50m"
          env:
            - name: CONFIG_PATH
              value: "/etc/cloudflare-ddns/"
          volumeMounts:
            - mountPath: "/etc/cloudflare-ddns"
              name: config-cloudflare-ddns
              readOnly: true
      volumes:
        - name: config-cloudflare-ddns
          secret:
            secretName: config-cloudflare-ddns
