---
cloudflare_api_token: 'ENC[AES256_GCM,data:1Svw/6/ILfmRFhitd54jy9CCPxMgwZw+pFWDUjEo5b1eRrEZjduMbA==,iv:LKNFwF2WQmvKiafAHJaPzJp6SzYijhG8FYeSOhGUe/I=,tag:mlkW6c2YB4v/0tPdZVQ/XQ==,type:str]'
sops:
  age:
    - recipient: 'age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr'
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVnBlRlNCU0RmRS9HaGhh
        K2RlT3BMNXZlSmlqUnBYUGtmR05rYnI2NVEwCjdUOXQ4U0dNakJSbHhodlBLZ3lw
        UDRscXRrNndldWIwQnVwbGxMTUpJZHMKLS0tIHYwVUN4UlBOWXRmTzBtV2xwQmd3
        cU5YNnQvRU96SC9zMlhaMW16cTJOV2sKKheBoDwiVdeZKo1b+B9uP6AGiF0OJ6Y/
        PG/6rMKNMaMRNQTwzZtilR0EkdpmgpnVgwtDTgpTAfOGwMsKCu5z/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2025-08-13T19:01:06Z'
  mac: 'ENC[AES256_GCM,data:mn6V4c8WAJ6SgOzZ6vhiJ9jCgBbITASA1jDZ8ivihGssh/7pwaxvbFziUjxenEL4WN2Ego7ey0v/nwR8kArUfSCskqF6Jp/OEjJmWq+Us1Mx50wBppfbj0o/JlOe1nuOeerOPK4NcwPJZyaNvP2wFwVDeWARk/HQVwRP+4A+BwA=,iv:0DR0vMoYE3nVYtWKoJVHIDkEpJCoB7LopNjXkpaslG4=,tag:6M9iTSC1QA0mjLsqm1N0BA==,type:str]'
  unencrypted_suffix: '_unencrypted'
  version: '3.10.2'
