apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/ha-pvc.yaml
  - manifests/ha-deployment.yaml
  - manifests/ha-http-route.yaml
  - manifests/ha-db-secret.sops.yaml
  - manifests/eufy-pvc.yaml
  - manifests/eufy-config.sops.yaml
  - manifests/eufy-deployment.yaml
  - manifests/eufy-svc.yaml
  - manifests/scrypted-pvc.yaml
  - manifests/scrypted-deployment.yaml
  - manifests/scrypted-svc.yaml
