apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - helmrelease.yaml
  - manifests/ha-db-secret.sops.yaml
  - manifests/eufy-config.sops.yaml

configMapGenerator:
  - name: home-assistant-config
    namespace: home-automation
    files:
      - config/configuration.yaml

configurations:
  - kustomizeconfig.yaml
