---
apiVersion: "operator.victoriametrics.com/v1beta1"
kind: "VMServiceScrape"
metadata:
  name: "tailscale-proxies"
  namespace: "tailscale"
spec:
  selector:
    matchExpressions:
      - key: "tailscale.com/metrics-target"
        operator: "Exists"
  targetLabels:
    - "ts_proxy_type"
    - "ts_proxy_parent_name"
  endpoints:
    - port: "metrics"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - sourceLabels: ["__meta_kubernetes_pod_name"]
          targetLabel: "tailscale_machine"
        - targetLabel: "cluster"
          replacement: "tale-lab"
