apiVersion: v1
kind: Secret
metadata:
  name: autobrr-db-credentials
  namespace: autobrr
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:SFaKT6t2shb5ERxZTF6WvR4ta7oNShic+uK1m+e47VD2rFAQ47IKcE9UutzgX9l8zFd56wkaegABgdniBD9hVw==,iv:INCRJa1AKZwfsZqHmWHvFIYoEI7EcHu4IhoVf4Lt87I=,tag:N+H6ZenOoNkHfyeZn2pdcw==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTi82cEFGcE1Tek12VDI3
        UDVwMkk0Z0VTelBRREJqYlFiTzFhU3N1MkhrCnhsNC9EY05NZ3NsOFJGWTFlMG1J
        ejg1NWhvZW4yeTRXSTkzTXZMYnFlV0UKLS0tIFY2Tm1MUGFkUkJPOUY1b052S1o2
        aEtNSUprWDk5V0ErNWJqS245R0sxVDgKVV1HwbQlAIIvoAV5di/q8jJ8CZLk6j43
        qU1u/RZ5bLil9L24jMZQmlIpBbAAx/qKf0oK8rcjDMdsa9z1Zuo2Ow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-04T02:24:53Z"
  mac: ENC[AES256_GCM,data:UqrsMc4xPYfIbeEXcRwbqQH3ltpLNNvSQBq+YihwKGIzixQzaOlXUbiDS6ITZMHL7FZH3PYm/U8iSlLgrya/Se/BWpoD3s3qzKurB+/pZ5wU4bifbKFc/NfRX6Xw5nNnzJhX7MjFt2JU/F9nh14INHWz9BEE5GMLuJZK/EFsCDo=,iv:yLRZzUM/Fn1FJlAR6MDLRjWn4OpzrQvM5ANupvIbN6Q=,tag:uueDjhax3T10aCavDMKLNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
