apiVersion: v1
kind: Secret
metadata:
  name: autobrr-oidc
  namespace: autobrr
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:hnKAZTAc/vqUTkzY9zc3Ps8fWZ2pPHZDrimvCaE+enJJWlc2+VDO7g==,iv:nbHuhiapxX00KQjSnIfODk8GfIY2Um6tkOA8FDZF3R4=,tag:C58VpYHPySVescasLqI1bg==,type:str]
  client-secret: ENC[AES256_GCM,data:v0BO0irE9kDIV+UR5OktizErPKV7dj8jU70butlCNQ/sDoMDHNGE5mUYfoUmENeiC8AnbgKGEynPEZug4RV56admMAnCDYTiSiVoPRHmb7NN9sCkjr0=,iv:PkhEqnLwNEwG7FM4kbwGOisZx2j1Wljs6iNxMVEbCDM=,tag:GoPrrHb9A9j1CPvagAkzpg==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOGVjYmhkdXM0amVGb0ZN
        OFRtODhRT2tFcWlRZkdNbWVXd1hYZ3lQNGhFCkVLNDJWaGVHTVlrZm5HK1BBd3Qy
        ZTBsWTZHWkJJeG9Hbm5HSjV5RTVhd28KLS0tIERoMEFSeWZMWk5Na051Zlo0Wkxr
        QThyUWlQeFFwdlN6T3FIVERrQTE2TlEKelpLDhY2vIC9GhdoDcgNtSWZ/TQ/9BeA
        CeFqI6Gi28dquqvjXrvIkEkb5wmnQE1Fr3baKH+Zg0Q5DzZoknZUgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-03T18:18:36Z"
  mac: ENC[AES256_GCM,data:23IhXYDNhKwmx6lNs4Ly9296mc/u6TLk1uKm0qK0BouzvxuQHK3qzxeIrZm2CZoZmos7+NVX6WjtAIRB+6OU3Gl+LEhgBTxATXaIENdtet7SNF1lkURG1KR0sB94dqrg2EBVCAwpgad71zoYkiPyCOOE1Bg/O94Kjk/O6F3P/rA=,iv:/0iJFpTWY7Gbm3jCVj/Tamq7wrbm8LaPn1X9xOQpvlw=,tag:rEGKJmDd41k+HzC6CsFEXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
