apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/infra/openebs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
