apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: me.tale.blocky.redis
  template:
    metadata:
      labels:
        app: me.tale.blocky.redis
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: blocky-redis
          image: redis:7
          ports:
            - containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-redis
  namespace: default
spec:
  selector:
    app: me.tale.blocky.redis
  ports:
    - port: 6379
      targetPort: 6379
