apiVersion: v1
kind: Service
metadata:
  name: blocky-dns
  namespace: default
  annotations:
    metallb.io/address-pool: blocky-pool
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: me.tale.blocky
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-tls
      port: 853
      targetPort: 853
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-http
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: me.tale.blocky
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
