apiVersion: v1
kind: Secret
metadata:
  name: blocky-db-credentials
  namespace: default
stringData:
  password: ENC[AES256_GCM,data:Rn9gH1xB673ganoag81Znv2F3Bgj5CCV995tHOVb6HkhkUSULJZqpG9sCJ0cXW3wtqmPiVj9Cv6X4G0Yy+h/gw==,iv:zLTYRJwT5FLWAK3njlQ8+yfL58d3EvoIOv6meYMiK4M=,tag:TFtsfUATej5l4E7l7p5ELQ==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS25Ob3dEQ0NRSFdKWXNC
        T3NGVW4rL2pad1RXU3EwZytiRlZtNVJpYVdnCiszQnJTNHlpQnJ0SzREeThPd3hK
        MWdjZnBybzgyQy91OFNzaWhVTGxUdUUKLS0tIDJRUDkrNFh0bThPcEJXWTgxYjhJ
        YW5KNUx0VXozT0hFK0piRC9lMENJWU0KEFcAA5Wc+DMT0NBpVGyf0QpKczRXcLbt
        LhDn1eTmktqD2/WyGXLmfYiepUa7SyQLdSDW/4zJjowTKRFpPvkMDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T19:45:01Z"
  mac: ENC[AES256_GCM,data:gsuAchaV1vYJF0sDs0aLF5/Sd31kkasisOjn/net5ek/jKiDPTscUGsiI0ccRRhWZfZCGRe6poghIlbW8mzWONi0xmqbLljg801idi71wTANA7IPSpqYeijgwLS8aGb0U9e7WyUF3UBreFrvJuXu+QL+/sOJDIIkAbf75JvAG1g=,iv:/WRHiRDKXCZi7w3l9KqNRs3yFYh7Yc0wO9trzG0o/vk=,tag:YVJZ9DTDqr5x5EIYlFVAng==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
