apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: blocky
  namespace: default
  labels:
    app: me.tale.blocky
spec:
  selector:
    matchLabels:
      app: me.tale.blocky
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      relabelConfigs:
        - targetLabel: job
          replacement: blocky
