apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gateway-helm
      version: v1.8.3
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
  install:
    createNamespace: true
  upgrade:
    serverSideApply: enabled
    crds: CreateReplace
  rollback:
    serverSideApply: enabled
  values:
    config:
      envoyGateway:
        extensionApis:
          enableBackend: true
        telemetry:
          metrics:
            prometheus:
              disable: false
    deployment:
      replicas: 2
