apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/tranquil-pds-config.yaml
  - manifests/tranquil-pds-secrets.sops.yaml
  - manifests/tranquil-pds-blobs-pvc.yaml
  - manifests/tranquil-pds-http-route.yaml
  - deployment.yaml
