apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
  values:
    image:
      repository: registry.k8s.io/external-dns/external-dns
    provider:
      name: cloudflare
    domainFilters:
      - tale.me
    sources:
      - gateway-httproute
    extraArgs:
      - --cloudflare-proxied
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token-secret
            key: api-token
