apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: bluesky-pds
  namespace: bluesky-pds
spec:
  sourcePVC: bluesky-pds-data
  trigger:
    schedule: "0 3 * * *"
  restic:
    repository: bluesky-pds-restic
    cacheCapacity: 1Gi
