apiVersion: v1
kind: Secret
metadata:
  name: pds-secrets
  namespace: bluesky-pds
stringData:
  jwtSecret: ENC[AES256_GCM,data:fUaMwN9qkBOldPMDeNgVnF0ZOi82bMOvLLUdwt4vSwI=,iv:sf1tVGpIS4qbRC0FGmdRx7R8bjABZGPcH4IaMXFAKGo=,tag:2BztKI94bFRgD+T7fgjYIQ==,type:str]
  adminPassword: ENC[AES256_GCM,data:JRWmlsESoUuzhphwNcDdsL1p1tL2MGSl3aqBczfHztA=,iv:DINc0ZtzcRXdHsgMX4hh718dsomn+iYQQ6QF2dEgIlg=,tag:B5mTU0whxStrJ039fD9GPg==,type:str]
  plcRotationKey: ENC[AES256_GCM,data:9JXOyAvGu7aQcW+nDf2pmE0ZJJjEiRQWqapVAPmdgF0qusW6xyxzpbqTKMfWK+uFFrZbyca+1RXMOn8W/O1OWw==,iv:TVuf0PNDP7a7T0kKevl6UA5q/pPx6SSJZ60swgyGl/Y=,tag:PAxrEyvdKvoe+chD/aZt0g==,type:str]
  emailSmtpUrl: ENC[AES256_GCM,data:gldH1aYxQFpg3F8cHX90djPev0Fn1RITnoDhodTOSrFWJoIRKJVj9vQ65vqcH1mIW9ISgBwh3yrsWFmLT3pSEynT2fmhJsXAj6ARg0hkXgTMu7dQ5rU6XINSeRHA6miCRsxfRgx0RIUvCKZOaTVwpM8=,iv:8mdMdkeFZXRT4taDN5eNgLZkrtSDqFNBo1zCjTv50jg=,tag:VFJQHIOwAXBdkSU8O1I3PA==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bkQ1Z1FFUUQxZFYwTkF1
        a2ZYV3FHeDBnQ1lTeHdQdGNPMnBaS0U2U21JCnQvZlYzZ0xQUnlwNHhYTStVNnVT
        WkdUV1g2N0wzdXZDNGZoWmdoQi9HcTgKLS0tIFM1RFlMYmtwVWxTT0tmNmMzMkdj
        S3FnanBmcUlLczVMU0lVR0F4NTFzSmMK2g8nzWw1iTLTAikB7Z8oLEhh/Bkt/00d
        +RrOzeKwIGcR29O6D9rCMQ0F3OpTjgB+YDs/bHEvLyWLCO5HunR8mA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T18:44:31Z"
  mac: ENC[AES256_GCM,data:VWb56wCDcCFHtqh+9ufMtpiAvVc1TvakWeHeIyj1UHWyI0AHZKRYyDXofhDE1QgvSug9x/NVJZgTKzrtTX8k8HT7LnnoX4BWQIXv/Aq5rmGVIvDLwWU9zIuBecUBgSiRtsg3ygEApkDppfrnA5PkjNgsYKjZCRrhX029PFSObdU=,iv:nsVaYyG1BqseXc6Dc5+S9u6Vv1+ftLM/wsyH6Jsrq+Y=,tag:5TowXXWsv3gETstSw9ZliA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
