apiVersion: v1
kind: Secret
metadata:
  name: bluesky-pds-restic
  namespace: bluesky-pds
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:N0VzekJ+09mTYETo7aQBlZnrGSitqeUb2I4JfnxLRQS3Zfr3g2KsN850dNqwD9qf3f541mPYwzcV,iv:htnkaqyEFr/YoTUYleKWh+xnUfkFs67JyKcHBT3kG+g=,tag:LzhPcoqcy+8cLsdLz3FMCw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:cqMY64igCT91Z491g/i42jw/o1KbpEf/CtFALv8Y80W2OP2DGuQ3zy9HuGA=,iv:Zz5hFtEmhn+tHA0OiqGgNn3nk/AqqRTuP+jAq1KPLHg=,tag:2QW/+XspeYXsnYETCB3IeA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:HNlgiwAK4CU59I2KJU2SOXG6am4=,iv:qMgItGf3H1V2z4mhYVj2gmBywGi7pnHn6W4pM9jreoo=,tag:z1oNreTmI2JNaZ0hT2cfgA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PIGaNiwWJhgcvC2Y5VpN0bOUUDdWEHv8TssW1rvFXC9PG0yoR/+fyA==,iv:UQsE0runbTMnHg8w23BI3M0mrE7QcWfBGfGKxQnJIL4=,tag:cP0Afeqkietv6ybnOgXNCA==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRjlBbHI2eUZkV0Z1MXNV
        d0NjWW5vV0NwZ1NLaHFudTJhQWl2NnFpUUFZCm5tRndmQTQvOTNUeUxoRXluMS9X
        ODVQWWJzRUtiVjdmZVViRFJOUGFrdkUKLS0tIFAyM01vd2FGeTNuRkp3ZXdET1E4
        MnA2alV0YXZHVnN1OVB2SXlHUERkU0EK1LRy6yq94pAd/X+47zq6r4QK6OdD8B99
        gPH1GPh7uH3rGL9E5DdbfHa7UwhrjQ14uqmHapoIRdMMfkTPQ6v9ag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-27T16:59:48Z"
  mac: ENC[AES256_GCM,data:pPl9/U7h1n2f5wMJ6uZnmfVQTckWPg8Jnm/CC/aACthk6VqmXcSbtlkBQQH5R5dGhe2RRE/Hx3Bi8jtE2d+iuZNN2VlyTBiJTNJroio7nmKHUfqnEwl4znLhMxmo14IIahxNsIDD0Y1k/BZ2WV9icqgHTRa296bz289v5SGxAsY=,iv:1MPhegqeouWV0zGEAEnhMDUNJT0BofNigMKCYjoeX6s=,tag:xRnwoOrlY9vntz46Z89u2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
