apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/infra/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  path: ./k8s/infra/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: volsync-b2
---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps
  namespace: flux-system
spec:
  inputs:
    - app: authentik
      path: ./k8s/authentik
      dependsOn: [{ "name": "infra-configs" }]
    - app: bluesky-pds
      path: ./k8s/bluesky-pds
      dependsOn: [{ "name": "infra-configs" }]
    - app: minecraft
      path: ./k8s/minecraft
      dependsOn: [{ "name": "infra-configs" }]
    - app: observability
      path: ./k8s/observability
      dependsOn: [{ "name": "infra-configs" }]
    - app: devtools
      path: ./k8s/devtools
      dependsOn: [{ "name": "infra-configs" }]
    - app: forgejo
      path: ./k8s/devtools/forgejo
      dependsOn: [{ "name": "infra-configs" }, { "name": "devtools" }]
    - app: gickup
      path: ./k8s/devtools/gickup
      dependsOn: [{ "name": "infra-configs" }, { "name": "forgejo" }]
    - app: wakapi
      path: ./k8s/devtools/wakapi
      dependsOn: [{ "name": "infra-configs" }, { "name": "devtools" }]
    - app: networking
      path: ./k8s/networking
      dependsOn: [{ "name": "infra-configs" }]
    - app: gateway
      path: ./k8s/networking/gateway
      dependsOn: [{ "name": "infra-configs" }, { "name": "networking" }]
    - app: blocky
      path: ./k8s/networking/blocky
      dependsOn: [{ "name": "infra-configs" }, { "name": "networking" }]
    - app: omada-controller
      path: ./k8s/networking/omada-controller
      dependsOn: [{ "name": "infra-configs" }, { "name": "networking" }]
    - app: home-automation
      path: ./k8s/home-automation
      dependsOn: [{ "name": "infra-configs" }]
    - app: home-assistant
      path: ./k8s/home-automation/home-assistant
      dependsOn: [{ "name": "infra-configs" }, { "name": "home-automation" }]
    - app: eufy-security-ws
      path: ./k8s/home-automation/eufy-security-ws
      dependsOn: [{ "name": "infra-configs" }, { "name": "home-automation" }]
    - app: scrypted
      path: ./k8s/home-automation/scrypted
      dependsOn: [{ "name": "infra-configs" }, { "name": "home-automation" }]
    - app: samba
      path: ./k8s/home-automation/samba
      dependsOn: [{ "name": "infra-configs" }, { "name": "home-automation" }]
  resources:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: << inputs.app >>
        namespace: flux-system
      spec:
        dependsOn: << inputs.dependsOn | toJson >>
        interval: 1h
        path: << inputs.path >>
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
        decryption:
          provider: sops
          secretRef:
            name: sops-age
