---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "smb-store"
  namespace: "home-automation"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "cluster-nvmf"
  resources:
    requests:
      storage: "500Gi"
