apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: 0.16.1
      sourceRef:
        kind: HelmRepository
        name: metallb
  upgrade:
    serverSideApply: enabled
  rollback:
    serverSideApply: enabled
  values:
    prometheus:
      rbacPrometheus: true
      serviceAccount: vmagent-victoria-metrics-k8s-stack
      namespace: observability-system
      serviceMonitor:
        enabled: true
    frrk8s:
      enabled: false
