apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: metallb
  podMetricsEndpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: metallb-speaker
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: speaker
      app.kubernetes.io/name: metallb
  podMetricsEndpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
