apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml

  - manifests/vanilla/pvc.yaml
  - manifests/vanilla/surveyor-config.yaml
  - manifests/vanilla/rcon-secret.sops.yaml
  - manifests/vanilla/restic-credentials.sops.yaml
  - manifests/vanilla/deployment.yaml
  - manifests/vanilla/service.yaml
  - manifests/vanilla/backup.yaml

components:
  - ../components/volsync-defaults
