apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-operator
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 60s
      metricRelabelConfigs:
        - action: labeldrop
          regex: revision|uid|url|ref|path|source_name
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: flux-controllers
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: flux
  podMetricsEndpoints:
    - port: http-prom
      path: /metrics
      interval: 60s
      metricRelabelConfigs:
        - action: drop
          source_labels: [__name__]
          regex: gotk_reconcile_duration_seconds_bucket|gotk_event_http_.*_bucket
