apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: monitoring-health
  namespace: observability-system
spec:
  instanceSelector:
    matchLabels:
      dashboards: "homelab"
  folder: Homelab
  resyncPeriod: 10m
  configMapRef:
    name: grafana-dashboard-monitoring
    key: monitoring.json
