apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-credentials
  namespace: observability-system
stringData:
  password: ENC[AES256_GCM,data:+h9h28KZRqAbesC0X24EsbMeOuyp7pxBEIkdVKiSB8iOgZNaK76CQ60cVgwZHCqPhhOMjHhJ8UMmJDpHfp8UMg==,iv:nw2GMh5AYrV5UUNeEWh4vqnZZUvpl1eLs1dC9GZpbwI=,tag:xg2XGoNcFTyCn0LGkO8qVg==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RStFejdvRTZ2VUx1b1Yy
        UGpaYllaU295SnJNVElEbDBIRjVWTGZCSmxVCi9yZ2pKY1ZJRWxOMFN5M0MvUmtZ
        ZCtJeHl1QUdqOWJzRUpMRDZZbldCWTgKLS0tIFlnSHBOQUxNYWhXQ2paNlJXU2d4
        Q09VY1JVWDYrbHZwaW9oUlJ1SGNVZ28KDlZEjXbmVeelPedoj1eBJMsebuMEg1dI
        D+vu+zv3KVtDu5dFnJmBgCiH2wn90L/CU0Hz7Hz5q6q0FR0fvkaA/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T00:30:34Z"
  mac: ENC[AES256_GCM,data:jO0rltm9fI9ijyRShFexiq4n+PSKVsJyNN5QByiKZPP0/snL4FRN9SoYdNnyo8LmxIsDpWeOmjcXqkdB5V17y12Qartj+Q583IdirEYsi6MA8OdosCfCQMf0Tdk8wyqVv/xwUlqjA6VAKK1nUEhmKfXiSdKrtjeMhT3pCVUBzBw=,iv:YS0lWmWHT8B3T/BFMjGj9M9qf9VwOk1ZATEJbH+VYUk=,tag:DRPoCnpfzKHoaAEM+GmQIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
