apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: nut-exporter
  namespace: observability-system
spec:
  jobName: nut-exporter
  targetEndpoints:
    - targets:
        - 172.31.42.5:9199
      path: /ups_metrics
      scheme: http
      interval: 30s
      labels:
        ups: cyberpower
        instance: nut
