apiVersion: v1
kind: Secret
metadata:
  name: pushover-credentials
  namespace: observability-system
stringData:
  user_key: ENC[AES256_GCM,data:OZdbpa9sMBs69YxWPeP3xUJoiheCORocXlN3cxb1,iv:WCu/gDAdgNgl0hoH/IXdBvk290v6Fd43G5xwqYs8hDI=,tag:gop1J+r9Icvf8fTw2ERBJA==,type:str]
  api_token: ENC[AES256_GCM,data:L39afbpDcbyRMAxxJxfnFzGaumXt4b/5jJd6w4gJ,iv:UPuRTy7eJ3Abf4j87eZlI/p4e/sU5L3wBEWP4qHWcgI=,tag:weg6EyuujCvwXsIUIOe4zA==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNTl4alF1Z3VKb0tjalla
        c3pnaVlKWkh5MzZKQ0FBMjF3M25pRjd5SzJVCjRZRXgrVG5NRXJpUitOTm4xdTFP
        VlJRaHR5UWZ6aWZPaTcvRkdCL3BHNW8KLS0tIE5GSnpFWVZKLyt6L0RrNjJ6VGpH
        ZUF1Uk1MQTkvbWdsS0xsNElWMm5MaEUKPnhmf08Hp2vOxNePsYDi6nfkzGKY/Mur
        XzSEhiRxvuLBloFo7N4d13JN7nlP+q9CSBC/sIylwxpCqX9alc2wxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T17:31:38Z"
  mac: ENC[AES256_GCM,data:x1iXF3XU90rwH4gCL4xb5DM4gmI/64/TWMAet3NurK/k0AakecBgPXAx9A2kHC05DpEQun7nf+VkhuEf0jZxAur2K0yqfilVeKu2V6WaU4WeHuT3Br46MCq8x7XH9iTI2MZYCOupLnWhJdez5RZvftI/P/z0hKj/XHeojUvyTW4=,iv:8zBSVipVJEjtETbZa9b2k7VQyhIjcWHCuFjkD34oWD4=,tag:X7L+OmkmK49SfrHKt/fmCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
