apiVersion: v1
kind: Secret
metadata:
  name: vmbackup-wasabi-credentials
  namespace: observability-system
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:MD/vo+2Pbcm0CTpHe7qaaAt8OO0=,iv:ghyR6wQ/LTdJEuG8ftmT0rKgUJMnQKdSKGtfQN2sDy0=,tag:b7EBsJZu5C4+ky7N5HoUCw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:mcT7zwt5OgAPnZBAY3bUaEsgmFXL9PGM87ZQd72JJ0BDDkgtqV5UZw==,iv:e0FEHa9bEpKzVtsodUnc+Rm6xnWr8PL3KF+8hjPYyjY=,tag:NTz3CtiwcE+/L3mNyITECA==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WitMYnpGME9ZRWxPekdT
        RXZSbE00eVhKRktCa052cVVSUGllZmxoeFdvCm9LdUV0QWdqZHRwVnpWTFZEUnha
        ejllai9ZTFBoU3NIYWlBSU1vQm1WL0kKLS0tIENITnpmUGlLaTFlU3kyQ1pMVE5H
        UU8zK2VNcUhLcWtzQmsydkNsUzhGSDQKuMVw+Ezb5oHtqzPU73SElb3yfJkbOt6h
        nlwdkLaJBt4Zk2lWGJc8NqVGMw6tfZdLyx2mvhbR4S4zISrrTl0VZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T00:31:14Z"
  mac: ENC[AES256_GCM,data:EGn26JRIDjdrv6IeQxBxQyAxs9gS7J7HEgddem1ntTtwS1A5+s0YMFASi7oHz/aMLh7paIjLBS9PTywS/1xB/AjQgXpIE28ppHL3O0k//rjuSwxLZbhbjir1uYV8edTjRVpx55+cq5KFCIGTY+I62+yZkb5F9+wJ3MsGRyXQ3N4=,iv:51kKH0N8hfkHACBfsV7kfjLQ2YaPf5zy04YtCi6uB1o=,tag:hkV0J2XURk5JPBcYvJBvtQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
