---
apiVersion: "volsync.backube/v1alpha1"
kind: "ReplicationSource"
metadata:
  name: "smb-store"
  namespace: "home-automation"
spec:
  sourcePVC: "smb-store"
  trigger:
    schedule: "0 5 * * *"
  restic:
    repository: "smb-store-restic"
    copyMethod: "Direct"
    cacheCapacity: "4Gi"
    cacheStorageClassName: "cluster-nvmf-ephemeral"
    pruneIntervalDays: 14
    retain:
      daily: 7
      weekly: 5
      monthly: 6
