apiVersion: v1
kind: Secret
metadata:
  name: samba-backup-credentials
  namespace: home-automation
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rk7sDamw2SpQZJ6j0kX74m1efLw=,iv:AYkQA7NpkYVj0FvZvz6vG49l+cXKwTRnZR1lGUfIWdw=,tag:DkwJ8se3spWfbI7H6Q6YgQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wrxSyocCeqE8yIYndLMJWfmV9/J5QxeGLC5jge49RI3f2Zqr1iJeHQ==,iv:XmZ4DIr0ih06TMtMamTEv9bzjeYfrdJUw2iFYLU30Uw=,tag:kvBkjailocSCGGRziVj5iA==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTlNycjduRzJBVXAwdXNt
        V0YvMFhQV2srejZ3QWZrU2NUbkxlNk9kNVRVCnhVejV4THcxT055LzA5K3pFMy81
        aysxTm9ZRWRLTjA2NzlmSHFVRjZOSkEKLS0tIEV2S1hseXMzQXpjWENWTThCVkdU
        ZnZ5NEtzTjJ5Y3hZYlFWTmJqbkxiUTQKZSLHPvQ1F/k1JLRfQnoIAzHFPRQPKpBi
        ENQ0o+l9NJPBq8BQT8d3qPEtuCRPJ2gCqLZVxxz31LzVL1FWWL/wrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T22:54:03Z"
  mac: ENC[AES256_GCM,data:9FmCISbgWAE7qS2cIRAO/9ySqz6hhJPZdioMY0FBB/C5asVl+IqoZxMr9EKR66nGCvvdQbXE1ElwV+jyNNq4icQRC1WIxmWGXGKXB0ElOjtfGOIciHKowrZH26NC6Iw2VLWQ0pmxKOet24LlzhQ4TiRK+ANQGQvrNAHboQJFOaU=,iv:AGE3N8OvGliBSLQQIHDYY5ggMdKuNayi2cWyADoAqdQ=,tag:qig9qs6jG6thu2GwtBAh5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
