apiVersion: v1
kind: Secret
metadata:
  name: samba-config
  namespace: home-automation
type: Opaque
stringData:
  config.yml: ENC[AES256_GCM,data:He+vRcQTnSq7vH8SNpyHn85ZURAHE+0bsGi0m5MIrqWi1gw+IOVi7ijn7xfKRR6fCRI1CvvdgbZiGTegaFCoEBlfAQ85IPCpGqfo2qQJ7/8wZMElepwORT3niP+AoR+Lh5TfYcGvC0g74Cq23dR+PptVoFtKUuN5f+17Nj1rDzDBrF80sF8zFXUu3x+ogjMUgcfE3eblfQsJOPtiqX1uBSHohMZBRyVCNSMSVZ3iy/FD4Na9Ek/1fhPqJAD4yzyCCVzmq3Z/dUpDSkVd5W34P6rrD3tCXInXLlCFERuVwB40kQPACYjMb2NFEZmM1bTZXXHKhDVF9q3MD5TERNgMNc2/LCVMfMwG9RfsMW8tB6Sm9sWDJd+9tbVujdxAztp4i0FmCAyXDc2ASM+EQ/8/0fakFS0USp5yZ9D/fyP0ST2E+q7qRPS4BoU+eMf5Q4KEpx1FnUSv4mq8RZTbVNd0t/uzD1D1aYPzG3+M/tD/XW9QbyttyKbmQKC3h3C+QQcpVbo3pEUenlTnf/NXlZQazTE7p4lfu/QhyYuPCfN0yM8JlH8IKswaQBacH8kIvK7ttj3eW0sx0XKdfaY7nB5IjN72tvnfyKzn5lPIQXEnAmV7LJ1R,iv:VK0f+NCro7q8go5Up1LhLTKMJGc/0HuMF61YuzJOm/0=,tag:9Y4DM3AEBM9eW3jFrI4SnA==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5c2RDN1JYU242aHBvWDFM
        b0xlQXRYTndGaDJaWllNY0dKdTdtWkswbmcwCkF3RHMyUEhza3ZJVmErTDI5RGt4
        Zm5JWWJBaERqY3ZHUkk5N0hlU0lOVFUKLS0tIFRWSE1xbEc4RE50d3JjYlpaNk5w
        eWdVKzAyWnFLUXlpZW5KejNqMEhDSkEKqGn4baR5gTAledK12Md0nR3MdmrfqkAR
        bbaOUCnB0r5hUlHwUKStT1HMLfzQbG0oNlpX548oP3nfVzAzxrnAbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-23T19:38:29Z"
  mac: ENC[AES256_GCM,data:lePX1qPTtGx9L0dpa3s6DEXe2koRaCefS0eYvcUD2rFFCxiIigarfmVFHQNV6nHaQbSXcwAO+6D/7PTljT8shBWhaR3SQ9AVxTiyT8BKmobv0e+0sqMFNs+oTOlIa58vZaa+RKcUB91uhD1OW8aOS1F1TDyBDEpUIT0w128TmYo=,iv:9d7HGz284kTu1aJ75pHnnCjWrBGdUNhI/m1xc48eOHU=,tag:9zbWiDvWPTCuP/8u3qFZ/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
