---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "samba"
  namespace: "home-automation"
  annotations:
    metallb.io/address-pool: "samba-pool"
spec:
  type: "LoadBalancer"
  externalTrafficPolicy: "Cluster"
  ports:
    - name: "smb"
      port: 445
      targetPort: 445
      protocol: "TCP"
    - name: "wsdd2"
      port: 3702
      targetPort: 3702
      protocol: "UDP"
    - name: "ssh"
      port: 22
      targetPort: 2222
      protocol: "TCP"
  selector:
    app.kubernetes.io/name: "samba-store"
