apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: flux-operator
      version: ">=0.40.0"
      sourceRef:
        kind: HelmRepository
        name: flux-operator
  valuesFrom:
    - kind: Secret
      name: flux-ui-oidc-secret
      valuesKey: client-secret
      targetPath: web.config.authentication.oauth2.clientSecret
  values:
    web:
      enabled: true
      config:
        baseURL: https://flux.tale.me
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            clientID: c87cccfc-0696-4478-9f25-1a7076314160
            issuerURL: https://idp.tale.me
      httpRoute:
        enabled: true
        parentRefs:
          - name: envoy-gw
            namespace: default
            sectionName: https
        hostnames:
          - flux.tale.me
