apiVersion: v1
kind: Secret
metadata:
  name: flux-ui-oidc-secret
  namespace: flux-system
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:cjVQJe8s4H26AoRzK3b7LH8zAh4P96fcbIzGrGXfNVI=,iv:N9fbGI90hWDElQjCf232XIY8Qce0EkLUbOPRMTZeExo=,tag:omEFqvRl0okzkuvYQhdd0w==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZW5QclF4ajh2c3V2RGZG
        TzQ3RUcySlJlMVJWdFpTc2ZNbmpscmNyMXhvCitXemptaFRFT2xxck90ZUI0clYz
        dWlLcCtzMi9qaTdFeXFqRElNbU9jNzAKLS0tIHFuak1ETkJpT3dvQXkvdW9qOGF6
        cTd2T3owL0ZXa213TW5sR2x3Y0dJbm8KukUspBUwksKkalpSAw7pIwflQVszsVhe
        GBy1830KILdCGxq2PCwgkynWt8J2HhP3rz5EiFQY4I0FdjfeYiK0Ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T14:17:13Z"
  mac: ENC[AES256_GCM,data:NQwqb5PWMv1mQEkE0xw1ahcziQVqxMG0ijU/4rs00jDIji52ocmErTP+BAwmqRQGxPpxY91CEYAl17zK11smC3IhdZqIwm5blca0tFloGkLM45pYDtWqHFZJ8SCAYBortz6jQHHRE3x7J1q+LUYW7XpZhGtXQ87/2Cuqc2qsBiY=,iv:jVmhfOvFmiQyc35S80rauDNcofNkSprmpk/alizuIYE=,tag:0LhqghYFBSwdlOsndZiMMQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
