apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-mongodb-data
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cluster-nvmf
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-mongodb-dump
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cluster-nvmf
  resources:
    requests:
      storage: 2Gi
