apiVersion: v1
kind: Secret
metadata:
  name: volsync-b2
  namespace: flux-system
stringData:
  B2_ENDPOINT: ENC[AES256_GCM,data:kCe/83vJkdHsejY1tniquQVok574P443ShE47ly9,iv:y+L2PUqpi72U5zZExB2CoiTaqop1SrI8vAQ2ZxLa+Wk=,tag:Ihg/YZlQXcQxdTIwedXjyg==,type:str]
  B2_BUCKET: ENC[AES256_GCM,data:bguki25uakxL,iv:Bb0AQrF1YLwFruslgzh+MA2nptOD08eI70ftUwNnE1Y=,tag:w2fmKas0Xx6JAm9epXHSFw==,type:str]
  B2_KEY_ID: ENC[AES256_GCM,data:6Cl7cvBVxbpdnn98h3IQjOyOXi3zNcUMqQ==,iv:iKKxDhvu3h9n9FnEL3M5IrlVht8L6Du33rPvKoL82ns=,tag:TgWcimzeKdqs0xtaffJQaw==,type:str]
  B2_APP_KEY: ENC[AES256_GCM,data:Xmt9PTEFaVNdadOhUXi0Xg90SA3uH4T2O4ZKK78t0g==,iv:RN1ooN/ThrIHnC1H4ft6cOin96J4A9+mmsNypsWaGmo=,tag:iswlaHiyHuJ/7+MyTKRaMA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:8Lr2M3vVNRdGn8r9gsuFYA9ouduZX2ixGHeUYidl7wq29GPjoaYCsrxl2No=,iv:nhy9EJDfny9Z7NEphm8mQ2VZCne+tXssCUDEcQU+yhY=,tag:OEoxOPieu4adEG+fk59WzQ==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNDZ1UWZGY3cxdTRoWlZD
        L1RFUFhRcUpJVHJ0eG0xSDYwS3hvMVV1UFU4ClB0MDRkc3RRSTdSMmhUcUVDRzZY
        dUhmRnV6N25wOUdBWGRFeWpuNnpWajQKLS0tIGI2NURKbXF3eHRSOE5BNitRS1lO
        bXZFNVpUNVUwY2YxSlNlQ0Iyb0FncUEKMb3uVvjTf1T/wALzOODliY1pbLoWyU+j
        2+asxTjcOXsR+xfDUh3D+ytGWmkDuGWsMcxgPrihMNr3eItaHzb06A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-03T00:03:16Z"
  mac: ENC[AES256_GCM,data:ovpbdlKGJ4wWr6gO2RjsvzojgkhkJveazRr4f6zhZ2m3TfnZSmPnC2ZHdtNQHN0dmPS6uI+SSvkky+Ly6D4zxxdolz8LafNoXhF8JqogKgzcfge7alRAc0ZPqU5NfE5eEhJDsp8KMYf82RLqasCIdp9sGmOfUMk9WhjITdoZWac=,iv:jSLF5I4bs9RtSB9hMIvGvrHIFcjo2VrCXkkLmUO5HT4=,tag:0dbJT1SmnqqbuwuC51tYQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
