config:
  timezone: America/New_York
  externalMongoDBUrlSecret:
    name: omada-mongodb-uri
    key: uri

service:
  type: LoadBalancer
  annotations:
    metallb.io/address-pool: omada-pool

persistence:
  data:
    storageClassName: cluster-nvmf
    size: 10Gi
  logs:
    # Seems like a bug, they named it wrong?
    storageClass: cluster-nvmf
    size: 1Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi
