apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - repositories.yaml

  - cert-manager/helmrelease.yaml
  - cert-manager/cf-apikey.sops.yaml

  - cloudnative-pg/helmrelease.yaml

  - envoy/helmrelease.yaml

  - external-dns/helmrelease.yaml

  - grafana-operator/helmrelease.yaml

  - prometheus-operator-crds/helmrelease.yaml

  - volsync/helmrelease.yaml

  - victoria-metrics-operator/helmrelease.yaml

  - flux-operator/helmrelease.yaml
  - flux-operator/oidc.sops.yaml
  - flux-operator/rbac.yaml

  - metallb/helmrelease.yaml
  - metallb/ddns-config.sops.yaml
  - metallb/ddns-deployment.yaml

  - openebs/helmrelease.yaml
