apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/repository.yaml
  - cert-manager/helmrelease.yaml
  - cert-manager/cf-apikey.sops.yaml

  - cloudnative-pg/namespace.yaml
  - cloudnative-pg/repository.yaml
  - cloudnative-pg/helmrelease.yaml

  - envoy/repository.yaml
  - envoy/helmrelease.yaml

  - external-dns/repository.yaml
  - external-dns/helmrelease.yaml

  - grafana-operator/repository.yaml
  - grafana-operator/helmrelease.yaml

  - prometheus-operator-crds/repository.yaml
  - prometheus-operator-crds/helmrelease.yaml

  - volsync/namespace.yaml
  - volsync/repository.yaml
  - volsync/helmrelease.yaml

  - victoria-metrics-operator/repository.yaml
  - victoria-metrics-operator/helmrelease.yaml

  - flux-operator/repository.yaml
  - flux-operator/helmrelease.yaml
  - flux-operator/oidc.sops.yaml
  - flux-operator/rbac.yaml

  - metallb/namespace.yaml
  - metallb/repository.yaml
  - metallb/helmrelease.yaml
  - metallb/ddns-config.sops.yaml
  - metallb/ddns-deployment.yaml

  - openebs/repository.yaml
  - openebs/helmrelease.yaml
