---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "vanilla-data"
  namespace: "minecraft"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "cluster-nvmf"
  resources:
    requests:
      storage: "10Gi"
