apiVersion: v1
kind: Secret
metadata:
  name: vanilla-rcon
  namespace: minecraft
stringData:
  password: ENC[AES256_GCM,data:bxvZ1zxTbtitQ9cMHbp1sOCKgtZRb/hwaf+Ys7WClLQ=,iv:RWg894sLtbDdU4r0w4OB+o7XrjbQxddS3rJZll0xcQ8=,tag:BLl1rbLMyipfxdkoMutFxg==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4d3lLb3V5VldEODB0Vnky
        SnNPbU5iMWtOeisvMTRtTkhvSHRob1l1OFE4Cjk1bG5NaG5obG5iOGxKWUpaWGo1
        Q2VudkNzNzA2NE9TZXd2Q0hPMzZ3d0UKLS0tIGZENVJqM1VoN3U2KzQwaUNRRzYz
        Z1hJWTdYSWlSMVpRalRITU5aOFEwbjQKTLtosAnCH9ZOhrQEckDeGNYeW0qD9K7+
        phLtfQ0Voao9mtOn5tjs3bEAcE2pETqwX62tFp+gWdBSzMzKB57CvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-02T04:44:57Z"
  mac: ENC[AES256_GCM,data:BqO7JEA5dnCLitLqMVmH+uyjXDoLotbYweudqnFCy//weELOSDzHp7PPB4svBtoYH65ZdCf78p4uernZGMknp08chKxH0Y5ZpF79Mdqz7NTOiaRg55+c9dfLX1HRmxVXtWukIjrMHXJ2Bc6ARWZF970au75y6xxrhXqhZKtZU3U=,iv:NRGXMae9h8Y2no7V1WKxIOrfJWOFnzb78/0JPqf+g1s=,tag:oZSUKLkdS6kic4Bvc9IN2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
