apiVersion: v1
kind: Secret
metadata:
  name: vanilla-restic
  namespace: minecraft
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NDzoMuneJ3T3KXvahzzCrokSfQI=,iv:XzMbx5rZnLl8CMrtMArEtNevn3UIARLBX2T40cFJ8Ts=,tag:M3NiEeAJHvxjA88csdQ41Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3OB1k/c7Ag23UP7NoA24HRE39r4z93EhTHNP0yNLoHU5Ye56Hq9ByA==,iv:BaIEFECoaDw1418Jn7OI2xCUuJaBAq2QEkUGgnvXotE=,tag:SzQ3Vh/4j6MVrqJoVBYn4g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:5fXXBG4lnAhgbNukzj3vani33iNWzbveZvBze3/9jWI6/EQEn4GL8Tq3ZkyNhoSQ,iv:7S/Kqig2+GBbQWeom8gpC0z58z956LsFWUozBXcwqQ4=,tag:GY9PMWWbhcYubBnUDrx34g==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:yfp2HcoWRblvD1tQTLglKhDInkVU2dPp5wLMZXLjnjqmHEtl5yDcIrPB39emBPfONc8gYEA509XS/tRjmPpj,iv:rdpfs52cQZtPqjF6NARoxeM7LhWDa3VQ2UI/KHIfYi0=,tag:FKnf3xFpQA0NaXqvz+V+rA==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcm9aWVo1WmZ5VlQ4SWpQ
        KzhHS2k0dGZQOStVRndXZ1k5WXA5MnRzaERrCm1HRnlFYS9yMWdYR3VNNkpjaVZT
        TWhMK3lKWEhqMzZSaFpEQkVzTUlIREEKLS0tIDFQUXJHSWxlTWVWcXgrV0JzVC9a
        VGdqU2xqYmY2QTlHQ3c3TkdyazZMbm8KtRM1UD1moOwNI+maAgd1UFDe4ANC6Ad7
        xrVQ0UxQX9gTTOPo8tJYcTUBSRSRAkbHkDCtrgakLWg9Y12wz9cb8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-02T04:44:57Z"
  mac: ENC[AES256_GCM,data:QWnViWkpH2Jzrh64+Ft7bZN8wN8mXC5OmdbOWKDIZXxq3MfWY8gFBVa+iDiZB05LvWUsfc78xUmSq9tI+qdJkrgQqzVSk1wyXSCtThUfwkc+g3pRc5CueJuMEnbZjBt/yZ8rYftR2DZ/Ptrar2+CbFZBu55UE4C4D28JGnVI/sI=,iv:6gW6hl0L6yVvWHYVX96BL+SlTBeiqVkvNx4N67xzJ1w=,tag:wDrcVv9uKUGuEL3zLxBiHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
