---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "vanilla"
  namespace: "minecraft"
  annotations:
    metallb.io/address-pool: "minecraft-pool"
spec:
  type: "LoadBalancer"
  externalTrafficPolicy: "Cluster"
  ports:
    - name: "minecraft"
      port: 25565
      targetPort: 25565
      protocol: "TCP"
  selector:
    app.kubernetes.io/name: "vanilla"
