---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "vanilla-surveyor-patch"
  namespace: "minecraft"
  labels:
    app.kubernetes.io/name: "vanilla"
data:
  surveyor.json: |
    {
      "file": "/data/config/surveyor.toml",
      "ops": [
        { "$set": { "path": "$.networking.globalSharing", "value": true } },
        { "$set": { "path": "$.networking.terrain", "value": "SERVER" } },
        { "$set": { "path": "$.networking.structures", "value": "SERVER" } },
        { "$set": { "path": "$.networking.landmarks", "value": "SERVER" } },
        { "$set": { "path": "$.networking.waypoints", "value": "SERVER" } },
        { "$set": { "path": "$.networking.positions", "value": "GROUP" } }
      ]
    }
