---
clusterName: tale-lab
endpoint: https://172.31.42.100:6443
talosVersion: ${TALOS_VERSION}
kubernetesVersion: ${KUBERNETES_VERSION}
allowSchedulingOnControlPlanes: true

# The IP address we use for the floating IP to a healthy control plane
additionalApiServerCertSans:
  - 172.31.42.100

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12

# We render a Cilium configuration and inject it as a patch into Talos
cniConfig:
  name: none

patches:
  - "@./patches/shared.yaml"
  - "@./patches/openebs.yaml"
  - "@./extensions/tailscale.sops.yaml"
  - "@./extensions/nut-client.yaml"
  - "@./cilium/manifest.gen.yaml"

controlPlane:
  talosImageURL: factory.talos.dev/metal-installer-secureboot/${TALOS_SCHEMATIC_ID}

nodes:
  - hostname: talos-pk9-lp1
    ipAddress: 172.31.42.2
    controlPlane: true
    installDiskSelector:
      model: CT240BX500SSD1
    patches:
      - "@./nodes/talos-pk9-lp1.yaml"

  - hostname: talos-z4f-vra
    ipAddress: 172.31.42.3
    controlPlane: true
    installDiskSelector:
      model: CT240BX500SSD1
    patches:
      - "@./nodes/talos-z4f-vra.yaml"

  - hostname: talos-74p-1fd
    ipAddress: 172.31.42.4
    controlPlane: true
    installDiskSelector:
      model: CT240BX500SSD1
    patches:
      - "@./nodes/talos-74p-1fd.yaml"
