apiVersion: v1
kind: Secret
metadata:
  name: forgejo-db-credentials
  namespace: devtools
stringData:
  password: ENC[AES256_GCM,data:FV0YYELF+TzKhXbZiphuFtdCPH6l6+TtTqypS+pTFnYPmXvYABJ9mcMUtnbo6IOtcJY3jskxvjItaP0m/g0Qqg==,iv:WZuu7BEVqO2WDxU23HbGlK1FeXkSGbB8eOIja5AwUhY=,tag:B6A8YJzqGX9tCaeLR5qHog==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6K1JKNHEvaVhRRUtBbUh0
        QTFsUFRsTG4vUEpudnk1aFR4eXF6NkdoUDBJClhSSTVNekhtSVArYUVvNkJwOUpu
        bWVjVVFYWGVZSVI1WlNucU41SXhjYlUKLS0tIE1XbEJsQzZETmpubks1V1lPZkpa
        aU9ORG8ycGdkb1ZrOFB5QjgyNW9pc0kKXH9uXr6u2GyKeCwbzQAqwHGHFGJuy/IC
        Nq73DiJTmGIwAWOpYs24UXQVtLFGKrBX+QBrxpYHrk38W1k2QZCxcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-04T16:00:09Z"
  mac: ENC[AES256_GCM,data:adEkGf0K38Jq6Zivp9F1W2RFry7bWiLgQofGttMuzEDVqujxNvqQRb2OYZeQ9oBE7a1D0WIeSqjwcEGG+3oq+j+8JVDnS7TTn8JTtLxZ7RW6knea9gVpj8InaDaIbMtW04NLX5JHiIwTl0BVX+Axd4dbfaMyl91vTrg/KMl4rp0=,iv:Do7iLcWbMrzFuSRZprwqbw6cu0NsPbDCvT06fKGatdw=,tag:Qfp90Tpe5Swkv03MgQkOKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
