namespace := "default"
release := "oci://ghcr.io/traefik/helm/traefik"
version := "37.0.0"

default: helm whoami-server

helm:
	@echo "👉 Installing Traefik Helm chart"
	helm upgrade --install traefik {{release}} \
		--version {{version}} \
		--namespace {{namespace}} \
		-f {{justfile_directory()}}/values.yaml

whoami-server:
	@echo "👉 Creating whoami server @ lab.tale.me"
	kubectl apply -f {{justfile_directory()}}/manifests/1-whoami-deployment.yaml
	kubectl apply -f {{justfile_directory()}}/manifests/2-whoami-ingress.yaml
