apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tranquil-pds-blobs
  namespace: tranquil-pds
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cluster-nvmf
  resources:
    requests:
      storage: 25Gi
