apiVersion: v1
kind: Secret
metadata:
  name: tranquil-pds-secrets
  namespace: tranquil-pds
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:BKKFty41o9LJjvr/Hy6FuLxfHuZzZsmPgddehMo62OXhBlT/spv7j0SkB5g2UL1lmNXBqYDYkrLqCoJXT5+XchlaYB4VxqpuCa8VqVVzqHpn2EwlWAzwda36KElNl5tHcPgxUOIBoO2fDBgvzo6p9TF6wp4Ew9Pu6has6YzvX+dyvdnut2Z7nVau1UUi1/xFKBtvmOJqnjoMkF6CR2QE503eLvDA,iv:9xobF/7ndKPF5533SdTT08qg68UwPRXThh7hInXsxLA=,tag:9eSGruAtbbgiBRiHksq/9g==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:ADH9aJqnnutR4ZgYiOE45BuIPLHRDuxuuvGqLSawDhnNwUTMKjmDqEm7kQuJHGxBoHw6Im6DKr//m4LBphHa8A==,iv:aq40/0ZNbJf12FaXjpp4GrsVkHC9D8QvdvZQzC2tcxc=,tag:CfB/EDpPHwKgIceph/jLYA==,type:str]
  DPOP_SECRET: ENC[AES256_GCM,data:KEMVWDu1Mp1t03OIZoXKaZu5JdlaEIlLRndLbcnw3JhJdhp+wAOivSb25joWi4INZRgin5fmCbCjMSwTA0tXgQ==,iv:udNXKTDvNNboY4pQYscMDRjDuzdWA6eDEJohZJMDuug=,tag:WCmewps6uQmllr/YMYFAmg==,type:str]
  MASTER_KEY: ENC[AES256_GCM,data:Ktcfx0a1OBxBBkxzJN3VM3dCfRj29OnvRWWqBRu0SqXQdRARASVilNQnv10IpkMggQcItwCqOTDYBWzjws0jSA==,iv:ajwpUv4rd4KNALl9O+JGQyctmaQQ6Bv1EEgn/Ma9pCE=,tag:U6vYiymjIeSP4e7f3CBLJQ==,type:str]
  MAIL_SMARTHOST_USERNAME: ENC[AES256_GCM,data:0B+0091J/hadSvjJa64xrodYO7Q=,iv:peU+DLN/7OwZoWkhuk79ZEPW3ikgiC2gQVdpuqE1+iI=,tag:aiYQqYob6yw/x8+aIFPHpQ==,type:str]
  MAIL_SMARTHOST_PASSWORD: ENC[AES256_GCM,data:rEiiDJOeZ/sZgQF4d4roXlsGI7KbHOolPT3o9hBX2cKm3ahbwp5SY/wjLSY=,iv:OvlsRAmQLkOSVkauUzh3XFV0FvFzsIxkYz0YFT68HfQ=,tag:Pa+wUjKLkkJ7Ov8qqw+4jw==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQkcwL2o2ck1POVhORERS
        NWluY1p3MG40NEZSM3BtQjdpTjU4TElweUI0CllCNldTaUJSNEN3b3J5Vk02VUZW
        N0tDVEVIS1lGeUxsMkUwUjZrbXFkOWcKLS0tIEtZVVk0L0xXOUZhMTQwWk5mVzBY
        cFNkNi8rZ1pPUzMveFlkdmd4ZlRJMVEKCxsg6sck2PaMgkY59QxkxHbNIsFhKHSs
        vjOflDJEi1c8WhsdVr5Bi3qLvuWo18aDGe/w+8goR0Sooa3hbYbLmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T18:46:36Z"
  mac: ENC[AES256_GCM,data:ZKZ/6gvbbsGv8x8BCZY20Y+DKUpodYSOONU/wp/h4THXLWUBfr+HSWUYDQfW5QYsHlspy14KNvME928kuw3DrSapk64D6VSeF1+0Ff1HPU2YrxoYGIQgYkglm1mZE1W2mAP0ffIKEIFJIJQfYQu9VWXMVGu9nbVtLJakdDG8tPY=,iv:Wc29/WBoFFspD71nBn7iap+r/usJvy6P2OjSm7/A+tM=,tag:nVOEpEBqhGCA1+eLoktN7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
