apiVersion: v1
kind: Secret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
stringData:
  password: ENC[AES256_GCM,data:NVnaTiOy5p+sbQpL1+oHjuBM2bEV+map1cCqlv7Erp0FPs8jrhT7AWY9M1zuJEnKjm4BePeLeY+rRH+TP6FgMQ==,iv:YdzLVhTDKJDH4adkqJPRrYi1lr8edWFw/xIQOHXI8sM=,tag:0eCiZvO5IXP4v70jpFN9fw==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWURzT1EzejQ4dTh5RG5C
        TXBUNHpDVkhJcHZZNW1uK3RESERXTW14ekIwCldRb3VKOEc3N0I2RVhLUXdSd1VO
        cXlkTU1vMW93T2dzNG1qd2FPUit1Y0EKLS0tIC9BelloV0xxZXNtNkdFelZ5emU3
        QnRpaGo1VjQvdW0wTXFTdGNBdEplalEK0AYoBlA7z587ISVDLXwpt76h6VOKctIW
        klNm9Fy5hHRtqoOe9rBfk//K9RSavcZL8d6+iqPs1jYQGYlu4jlpqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T14:24:42Z"
  mac: ENC[AES256_GCM,data:eeUveXX5rvGXt5G6qh84BfOX5W9HpllQ0ymRhv1n3Kgy82PdcgdMbAdC81OWouLjeLf2X2kh1jmWyFbSlWJ7AEi6CrQ9gO6Uoewbg/C3whjxoqCoqX5u/bCCIVpISP3zxKwzZoMYkgvuw8zVjhodO6KKNGLB3NTCSDOD0y/AD/k=,iv:ezVkGzAtt0mHTQ5zDQHFqnueYPo1WIiKd74lrD9vfh8=,tag:7xoiEtm+Xrpw5nQlpNw0AQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
