apiVersion: v1
kind: Secret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
stringData:
  password: ENC[AES256_GCM,data:8OA9ETf5JBl+1S7Yrw6zIFm74uvvltbPMyllFbobpiz3N9ysXJ8Zo1JsK+Upjud7adekUWMKNOgzdEocGtrwMg==,iv:7i37/JpTpKXfnwzBlTsxOR9eilWPYHwym5uVpWouoQY=,tag:6n/5fAvx4h+ZlFwOQVCvaw==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERFZSNTRKa25NM2lORnJR
        bWc1ZklxdEJyZEhQSmxKc2VMUnFmdG1ueEdnCk9MZlhyMEJyVUFwQkowZ3JWTzhW
        NWJOdHltdDU2azNoSzlNZFJIS1BhVkkKLS0tICtNZHB3M1ZSNmI3UC9ZKzBxN21a
        K2hDWEZkTGJJc3JQbHQ0YUcrSkt4bUUKtAxo2+dJi0h32K+x9x6mNEWU0vLNpaU/
        0ToGM1f8I+p0DJ5k9NTVRGJHQqxjh3cCg7szKcRDWxNzi7FmHKToLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T14:03:49Z"
  mac: ENC[AES256_GCM,data:lxOxfzrWj4YKa+SJiAhmFQva5WZlQV0N9BygxZJpKuURHTRNH3448MKhb3WG1Pfcb4+NrUHfIAs55N5u+2NvsvGAvuSGAVCMDXmE4dJEZKlwpy8YLtMVrmQZRgrbtqZxHNKl25mSQAJkeHtEQRjc7bhTa1VPNQo3Lue9SOf2Irg=,iv:dt6ObyERscC5GvwC+t2oK7eRFQIJ+I9wj1ZoIiBxbxY=,tag:KYeM3+EOEmJW6t9AKXnKOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
