apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: forgejo
  namespace: forgejo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: forgejo
      app.kubernetes.io/instance: forgejo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
