apiVersion: v1
kind: ConfigMap
metadata:
  name: omada-mongodb-init
  namespace: default
data:
  init-omada-user.sh: |
    #!/bin/bash
    mongosh -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin <<EOF
    use admin
    db.createUser({
      user: "$OMADA_DB_USER",
      pwd: "$OMADA_DB_PASS",
      roles: [
        { role: "readWriteAnyDatabase", db: "admin" },
        { role: "dbAdminAnyDatabase", db: "admin" }
      ]
    })
    EOF
