apiVersion: v1
kind: Secret
metadata:
  name: omada-db-secret
  namespace: default
type: Opaque
stringData:
  mongodb-root-password: ENC[AES256_GCM,data:aIInhpDtP48cEH4coimfjAjUe+3N+FinGlSs1amDRrI=,iv:4/L8CN4uNhhwNVa3+g+dc6+XyC+E2AdrPkEm7+CO2D8=,tag:9a+tIs7AVM8FR3n1JtYT1g==,type:str]
  mongodb-passwords: ENC[AES256_GCM,data:UFqn0VCYtwvHVYiNCFlJ36ZCEv0e+hjiGw4L+kk3Pp4=,iv:PZlGLjQeQN7qOeX4bs6P3SZvlWKUkwdeG5JVnpN86os=,tag:8zMhohaZrTOfj5dzqKRDyw==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSGtWb1lpRXZGNDNTeFVQ
        QlVVZ0Qwc3BSRCtqOUYrYncwYWhSaGFhQlNNCitxNVl4aXk1VnBsZmdxR3lCVEFi
        bEZuaGJHczVSVHdtMDZnZ2ord3lCYU0KLS0tIEovbG9WQmlOSVZBREJWdXI3bENL
        TzVpdFFpZi81aGlINnA3bVdISEZOdVkKR/IWxFh+TU7g1XxXsoDLRRr0dxLoCN49
        27YqJRueXPqz2yeHPjr+VJcwy+Kc5ID+fgDwptf6iqBMXjnHbLgfhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T19:34:18Z"
  mac: ENC[AES256_GCM,data:LMSmfnYgCpH0QsSu6JWWmAg16MDckymQIPfyDlKJQp56cSREMQM3tT0DRxIf37uSm6/KXm8FdqF5cXe0NxtLU6/BtPR2EF7ENos504NA7Xvn9eFU5S5frR9Ira/ROaO319nM/z3Zo2u3+zvuoLtn6AY/UPMzjd4jFJ57m+23mio=,iv:AxEQgaa9qd3Uy4JqX9gw7CISk/a/d+620hLhlLnqgvE=,tag:/I+1qZjBc1rpS1trJV2rKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
