apiVersion: v1
kind: Secret
metadata:
  name: omada-controller-restic
  namespace: default
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:1kPb1X8tkxQFL0MYIPxsZkWlf2b0nHVJpUs9lcMrvIE+ehrayeLtMLY9k2FoJcvPDwznI6UvidfAVpP6mEM=,iv:BuOD/Cvtc0txnsII2GqgNBY72Mq793yet6C7GK/mnSU=,tag:QUBfWDWqchouGB0/pp91Iw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:LF6Uk347Jln5C5VN3hyiQsfr9+Z5i+foBv1+bdPq3Yf9GnwTBra96Ehv0/s=,iv:yekL6WYXWEygUuhyjmorWKXFneAOOXMca+M6A263D+8=,tag:kfbBl1t1hJU342o72VVI+Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tQBUB80YWBqwZ18wkUhFCBny5bE=,iv:MF762wmpfxMCeOET3f6OWrnK9t/6U9+pcKWXrEGif7E=,tag:9Za4FAOBY9th9q5uN8kW4w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rVKQFIqv4m+BV1wAk64l9IaiXNKp//iXG2I5C+f8qJoDYznVN1u/3g==,iv:ExCrYu+HN6o2phVpTWsBSBSgiVE/FVlJrBJ+x6Dg/CI=,tag:HeEKM2r2De+kbiWzs6wn+g==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RldDajhQeVdOTldYTXgz
        YWs0bUxhdW9mZkN5YnAwYXZhaGZSQVV5YlVvClpVUHRiMUtuZEhiNXE3c0pXZFlw
        bHk1ZWVPbDh1SE1Xam10MFBTQkUyQ28KLS0tIFpJKzhLN1VBd2NockFkMXdqRkhU
        Z3RQeGVkWGR4VDY2bk5mcnFXVkpCWU0KQRDlxFyNHyPdrgW4XgGYnowCI2RBC3Zv
        hJe4HLCs2jWbBwpCrP0DZZdU/h8f094ccr0l9epuH+P9gNZ/5Kcibg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-02T16:07:05Z"
  mac: ENC[AES256_GCM,data:GJ9Qk+fDPIrx6WJESRqvhxSCzQDMwNXLunPFN38qiaV6RvwUV6v4nzFtvwWLJDoB9WDgluoab1gIkYd8NVYdw9lmxIC7ZyeW3g8TVEScG4bschPKE/lE2Hq1qgeIH9u26St2Intc+UsgZhpasa3njuXKDeSXX4AMlj4WUR89Lvg=,iv:/Sn3zkN/bGgP6Fn/fA4ga+vDNv2u/L+v/7PQKZsEktY=,tag:N8vtfMPgxCmHBK0k4ESzCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: omada-mongodb-restic
  namespace: default
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:cNhKDMNLfoCs0bYPc9VY/S3rtnZz+IcyAEp1iJuDMBcdrjE1wMR8fZ6SQtAuGyFZ4yFtweeQgNu/nOg=,iv:vWh7zJoZ/2MpLf5W7J//Rm9yxzUJK+VARiw4f16NMDU=,tag:5GTgnmbVhG6bkTboJbbJfQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:uEu9lP/3As7P6UUkpfcK0I3s9RDRfUtLJ2Ta9dBNMGpBFYEUQBBgTHZHwlg=,iv:XQqJ+hv8aQ1I/joYWf/g5olyN60CA9cR0hgYDoPlKfU=,tag:2dp9L8t5M/orSNZcAK3tTQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:uDpY3LFHMm8gc+IjNgAOz3NSOeg=,iv:OXSIfdeKFAmCxgxvBdX/bTbHu6+bRS/D5o+Lx/nuyL8=,tag:8rE9meX8FbaQ24yrIgfKvA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MOZ07jugA0OFm1i5pRYXcKfIZu8SVprzWoCvv7nxm3O0aad1invGsA==,iv:R3+b6pc3TnG8q2Kp2xR9lz5CXMZ6hHERlL+BuuHn0yQ=,tag:mA3CehzDI7ehoqabEzfRhA==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RldDajhQeVdOTldYTXgz
        YWs0bUxhdW9mZkN5YnAwYXZhaGZSQVV5YlVvClpVUHRiMUtuZEhiNXE3c0pXZFlw
        bHk1ZWVPbDh1SE1Xam10MFBTQkUyQ28KLS0tIFpJKzhLN1VBd2NockFkMXdqRkhU
        Z3RQeGVkWGR4VDY2bk5mcnFXVkpCWU0KQRDlxFyNHyPdrgW4XgGYnowCI2RBC3Zv
        hJe4HLCs2jWbBwpCrP0DZZdU/h8f094ccr0l9epuH+P9gNZ/5Kcibg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-02T16:07:05Z"
  mac: ENC[AES256_GCM,data:GJ9Qk+fDPIrx6WJESRqvhxSCzQDMwNXLunPFN38qiaV6RvwUV6v4nzFtvwWLJDoB9WDgluoab1gIkYd8NVYdw9lmxIC7ZyeW3g8TVEScG4bschPKE/lE2Hq1qgeIH9u26St2Intc+UsgZhpasa3njuXKDeSXX4AMlj4WUR89Lvg=,iv:/Sn3zkN/bGgP6Fn/fA4ga+vDNv2u/L+v/7PQKZsEktY=,tag:N8vtfMPgxCmHBK0k4ESzCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
