apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: central-postgres
  namespace: cnpg-system
spec:
  instances: 2
  postgresql:
    parameters:
      shared_buffers: "256MB"
      effective_cache_size: "512MB"
  storage:
    storageClass: cluster-nvmf
    size: 50Gi
  monitoring:
    enablePodMonitor: true
  backup:
    barmanObjectStore:
      destinationPath: s3://tale-home/cnpg/
      endpointURL: https://s3.wasabisys.com
      s3Credentials:
        accessKeyId:
          name: cnpg-wasabi-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-wasabi-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
