apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: central-postgres-home-assistant
  namespace: cnpg-system
spec:
  name: home_assistant
  owner: app
  cluster:
    name: central-postgres
