apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: central-postgres-backup
  namespace: cnpg-system
spec:
  schedule: "0 4 * * *"
  backupOwnerReference: self
  cluster:
    name: central-postgres
