apiVersion: v1
kind: Secret
metadata:
  name: cnpg-wasabi-credentials
  namespace: cnpg-system
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:TEuGWy8AQ2rlQkH4C+/aAhs8+PQ=,iv:+dUG6q0qJpa/yGCBMzZHAP+vckio0mG2h/M5d9fziVw=,tag:OBLG3+8fN990KL1wzrgWeQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:wFEoLGnuDXO0WKUCU1IYivsmwdPJI4hs2r7rBFpra4eCHj1pJJ+KJA==,iv:9TQRBSaJlPAcsL2c+TrC28sRJs4oLxZLj5MG/6DIkhs=,tag:9xz+Prc1cNPShAcY6l2HFw==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZUttdjRjcHpuWklHUnM5
        NHBCRVFqcGdhd2FsNUhsSjkrR3FBOUY2eDIwCnloSHp6SEx3Q2IzK0VRRllqOG9P
        cmtrbEduK09ReXF2TGdHdVRmOUdmOTQKLS0tIDc0MERMd0xvWlduRyswa3cxLy9E
        K2xGa1RwdjhZNnUvVGZKSmprVWpsWVkKFq7+2i5BZf/++Mwo224TZUlT51uowDa7
        8G0J+b5tH6nAN4oMMrg/ba/XWkYp/WCv+vo5D0jRcbyZdZjyKmhgNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T23:19:26Z"
  mac: ENC[AES256_GCM,data:i9qySywI0Z+uu/dlikzI+b36jEl3tP4LecjV2OkpoBvFJG6DJRgPSy2gsm0AH2h7tv8AXP5cR4zFTYltnxA01r7ZwKyrzT4VHFgNhd17g3OdIWNjkGoB6fvDFxhIasi5gDDS0ydn6eQyfu8PwmRWNnCuslbXGCwZISN+oW5eqZs=,iv:6oBovL9ddU9QL1yId0h9zebSyc9oyTmMPE6OrYLxUFc=,tag:hf+wU9Uiscy/BSXFkZCRBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
