apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  url: https://charts.goauthentik.io
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2026.2.2
      sourceRef:
        kind: HelmRepository
        name: authentik
  install:
    createNamespace: true
  values:
    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: secret-key
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: db-password
        - name: AUTHENTIK_EMAIL__USERNAME
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: ses-username
        - name: AUTHENTIK_EMAIL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: ses-password
        - name: AUTHENTIK_STORAGE__BACKEND
          value: s3
        - name: AUTHENTIK_STORAGE__S3__ENDPOINT
          value: https://s3.us-east-1.wasabisys.com
        - name: AUTHENTIK_STORAGE__S3__BUCKET_NAME
          value: tale-home
        - name: AUTHENTIK_STORAGE__S3__LOCATION
          value: authentik
        - name: AUTHENTIK_STORAGE__S3__CUSTOM_DOMAIN
          value: s3.us-east-1.wasabisys.com/tale-home
        - name: AUTHENTIK_STORAGE__S3__ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: s3-access-key
        - name: AUTHENTIK_STORAGE__S3__SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: s3-secret-key
    authentik:
      avatars: "gravatar,https://github.com/%(username)s.png,initials"
      log_level: info
      error_reporting:
        enabled: false
      email:
        host: email-smtp.us-east-1.amazonaws.com
        port: 587
        use_tls: true
        use_ssl: false
        from: noreply@tale.me
      postgresql:
        host: central-postgres-rw.cnpg-system.svc.cluster.local
        port: 5432
        name: authentik
        user: app
    blueprints:
      configMaps:
        - authentik-blueprints
    postgresql:
      enabled: false
    redis:
      enabled: true
    server:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
