apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  url: https://charts.goauthentik.io
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2026.2.2
      sourceRef:
        kind: HelmRepository
        name: authentik
  install:
    createNamespace: true
  values:
    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: secret-key
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: db-password
        - name: AUTHENTIK_EMAIL__USERNAME
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: ses-username
        - name: AUTHENTIK_EMAIL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: ses-password
    authentik:
      avatars: "gravatar,https://github.com/%(username)s.png,initials"
      log_level: info
      error_reporting:
        enabled: false
      email:
        host: email-smtp.us-east-1.amazonaws.com
        port: 587
        use_tls: true
        use_ssl: false
        from: noreply@tale.me
      postgresql:
        host: central-postgres-rw.cnpg-system.svc.cluster.local
        port: 5432
        name: authentik
        user: app
    blueprints:
      configMaps:
        - authentik-blueprints
    postgresql:
      enabled: false
    redis:
      enabled: true
    server:
      strategy:
        type: Recreate
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: authentik-data
      volumeMounts:
        - name: data
          mountPath: /data
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
