apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - helmrelease.yaml
  - manifests/authentik-secrets.sops.yaml
  - manifests/authentik-http-route.yaml
  - manifests/authentik-blueprints.yaml
  - manifests/apply-blueprints-job.yaml
  - manifests/authentik-data-pvc.yaml
  - manifests/service-monitor.yaml
  - manifests/grafana-dashboard.yaml
  - manifests/vmrule.yaml
