apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - manifests/authentik-secrets.sops.yaml
  - manifests/authentik-oidc-secrets.sops.yaml
  - manifests/authentik-http-route.yaml
  - manifests/authentik-data-pvc.yaml
  - manifests/vmrule.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authentik-blueprints
    namespace: authentik
    files:
      - blueprints/brand.yaml
      - blueprints/identity.yaml
      - blueprints/flows.yaml
      - blueprints/applications.yaml
