apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-secrets
  namespace: home-automation
stringData:
  secrets.yaml: ENC[AES256_GCM,data:e4LhtNwRrJQq7ei0PwAUXX9HkC5NUjuj5+0aUYCOoZ1GdY/FaGKpwdw7lYO/toT0EoLbd+5wUiAgRaCMovPvqYotGrsX3fH9woapzF+3BNyerkAeV+SzQkU/M/PpxCWKB7gR3cTsuU9Q481TUn2TOgOp1tGPvrr04V31yATHC1ZaEiLQ59BVXsmEehBWQaLexAHLgBFL+TFc7Zg7rQGKPBQTMqTnt/6HKP+q92wcGpjY6wtwiBoujoDH/wQ2mFR5NLMsaU1vuWkTxv3swSkWsP5qIpHDjSWXsc7STeRFHhI/bToRhtna8gch7FeDelLUjRWgUOWd7Qb9FGcHuEA=,iv:265mQeNmB+hPuVzpWLqIRyXa+JNSDmnITxC+XTS2A8U=,tag:6DfQgyRPT7ytIxehUIFNLQ==,type:str]
  scrypted_username: ENC[AES256_GCM,data:Shz7EhPQhhior10DpA==,iv:WiS1rMiVeRF6hsTYBufO43VBhpWNWTsKsrRsPKwdZLY=,tag:AIxLhVgs8VgngVZX+NpUjw==,type:str]
  scrypted_password: ENC[AES256_GCM,data:zh77ck0vfEKiWC4cJGJUTmm8yW0w/5ggGnuBiD5G0qU=,iv:JL2Ngt3k6UfcOrGm85hO+s6t0d0aKjqLJrbzBNvqXMM=,tag:sxJQTfBon5dkYPZH+mOWDQ==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VFRlSHVrMkdrSE5oWEU2
        a3lweU5JMmRxM3J0VzIyR2ZZTzZURGEyWW5rCmwrMnIwSjJQOFAwSkpOUGFNV3hG
        cURONUJDVVQ2NmRzM1V2Q1hpWnhOR2MKLS0tIGE4VkpDVkttOUxSMzRSMWp0VE1u
        YnFxQnNZVGN6eWRrVU4vVnZQK1Flc1UKPKqvI6wOASxKpw8Y8HqQtNLOY9Cb66yv
        JuLZuf4M2AommK1Pqg/iuuN19bBtNG359nCMeUxlNJryeR08E5WdSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-18T19:39:53Z"
  mac: ENC[AES256_GCM,data:EnH7QwZXFaLX3PR5mTF6L2cVnbYl95fF7E/MukPc7GBL+VCkE9U8eaQehAODlmDmZMZnv6ag8PQDvq50fa9W0uwuI6kKGsSdp5vG8acXezn+hwhVOrGf7rMQx9G2LMvpECIYSo5nYuPlORklr+Iq7Re4ICWKGCazMNhGxlWQ92g=,iv:Fg1wklJqQmYW++FNUV/maXrWG9AlMxH3jE3V9cOvdNA=,tag:7q5rwynSeevdiyLkjMVlDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
