apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-secrets
  namespace: home-automation
stringData:
  secrets.yaml: ENC[AES256_GCM,data:GseEuRkTeqkk+eseA1NXWN+o0+PQEXN0hX1A0UZtMHTEYuapOafHIPxJUhiBKbuWLjPiMdU7IzwBS1efZDv7tEU1enbjEg5MYyHcwm8aYZJKe+zOSwNWOnrIgIjV1/cJWIxox9OGGlY8n4zi6wbJxNbinPQqf8A+bLVyibmvurVYZA/2dAyWRiY0fge0JzBUbUOdELnAFq+pFIlDTtPlMjMemFNVhh1PIg==,iv:ywPMUx+FPFWYEAsIFK/q+XQKDDqaoG69srXyh41ky+w=,tag:P3tFkZ44NzzDC+AwSczXGg==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cWMzb040SWtjbENzYnUw
        WlpKUmhVS3ZWUlVDbklKS3h4cE5PMzV3WTBBCnorTnFZUUF5Sm5wZ0gxcTNCam9D
        eVVrYU1XY2lKYzZFV2Nxdk9CVVNNakkKLS0tIDFPZXd3czlYcmVyZXNzcDQ1Rzlz
        WjNoZDRoNXlaQWZjSm5obHRYc3YzSlEK6xTobzPlWaYs7ZzbrdMUv0l6Mq0lsibh
        fnvdAVa5dQPHrrkVhLfYbHk9YF3Cogpgste5l3NBsG1iUQ1gIFiPng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T01:31:23Z"
  mac: ENC[AES256_GCM,data:hw4KJRmn67WYpOtw3PYrt8qGbFSxC7liUhrtrByeyIBxKf92vC04wYjXY/aH6DC0cen0s+6GWdNDZUryYUvC2WUyNdR7JTQ8F7Qmb5RmDKi0z8hVZWSnh1z4+0LkmFncATWQNcgNyaEFPMdg5/veW/pjY2Akxhp+8XJhiZJiClo=,iv:Ntv5ZWgs04beSG8tJ5iHZvVSY2cRbRyGgN1Sq60ccpQ=,tag:R+EhYk6LiUY466idWbEaAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
