go2rtc:
history:
logbook:
media_source:
stream:
sun:
zeroconf:

homeassistant:
  name: Home
  country: US
  currency: USD
  time_zone: America/New_York
  unit_system: us_customary
  external_url: https://home.tale.me
  internal_url: https://home.tale.me

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 10.244.0.0/16
    - 172.31.42.0/24

lovelace:
  dashboards:
    lovelace:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Overview
      icon: mdi:view-dashboard
      show_in_sidebar: true

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 30

homekit:
  - name: Home Assistant Bridge
    port: 21063
    ip_address: !include homekit_host_ip.yaml
    advertise_ip: !include homekit_host_ip.yaml
    filter:
      include_domains:
        - binary_sensor
        - light

  - name: Front Door Lock
    port: 21064
    mode: accessory
    ip_address: !include homekit_host_ip.yaml
    advertise_ip: !include homekit_host_ip.yaml
    filter:
      include_entities:
        - lock.front_door

  - name: Garage Door Lock
    port: 21065
    mode: accessory
    ip_address: !include homekit_host_ip.yaml
    advertise_ip: !include homekit_host_ip.yaml
    filter:
      include_entities:
        - lock.garage_door

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
