apiVersion: v1
kind: Secret
metadata:
  name: wakapi-db-credentials
  namespace: wakapi
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:Arak4IMvp0/LKFNH4xxY0Ec4RtlFOOcjUGPieZZLmJuYtUOxzHvyaXUYyrVOeoJJhD+RYEYnt7SDDSKVyQD1DA==,iv:q6BWDqkCkZ6j8p/T2TZY+mKG/FHVlnVLLhtOx1y+g4c=,tag:D5FkVOaV2zhKp3sVXSPTIw==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbmpRRi9rc2QrS1VlZmtz
        UUtYaW9uMk51UWJqNkdPWURwVEE5WmxIbWc0Cm9OSDRtdnp2bTZwNmJRanhTSGZT
        Q09RdWdPVnBONnUzUk5WWThMVHFvU00KLS0tIHV0MW41Mmd3OXJtZE5XcXpUZUtu
        UitKYmdlTDBkYkg2Yk4xaWoxeDg1U28KQ26+0hahdDEPFPhYBDkk8Dt0k/tmYuXV
        U/aWP1jU28qZMOcgcl4cy5OBFpdAslXPQsmFaS8XGfipgsmH8U9DKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T02:46:48Z"
  mac: ENC[AES256_GCM,data:qzqAFFECj7K01SAhZrj2SlwG+XaG5PQoO7YTvDGBfhlsjkHIJN25YZSf3/5Idxf9sNtJN3RSxNwGJ/e0DIcoDN2ACAAq7JNIqcttoaekBkCtgbo+q3M3tf4RzO3RkD7+c4cPv1sFgg7uk7PGEij8L8mHoCD/S42p4EGOmfZaTYA=,iv:bHwVXEUyOnJZuF56Mqt+a+YOEQwy+cUtNUk4ESqprp4=,tag:m1TUKY3nczyb8+ICBjm/4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
