apiVersion: v1
kind: Secret
metadata:
  name: wakapi-secrets
  namespace: wakapi
type: Opaque
stringData:
  password-salt: ENC[AES256_GCM,data:BWRS/30XviVWl4xj+qO3I1JbtBZdPZ5F9pgiL6xm75g=,iv:aPW1ZnGpL4qfpCzZH9tV39vQBvYvFOsmHz+XqbrVXSU=,tag:8P3hpzpG3IvGeqZjRkeyPA==,type:str]
  smtp-user: ENC[AES256_GCM,data:kqQlsAMJKZw7v0yXzEEXltrusOQ=,iv:WueXDinNLhtK97brC7K9TnyV4rgE2VFN+iI9B7gak/g=,tag:dERZTTaAQ4tBj+p180G8qg==,type:str]
  smtp-pass: ENC[AES256_GCM,data:6VhSxvMXe9e8i+EjkiV2GiHFnXNTna+69eYZGs2s0Ip5ieVOWHBCT3LtrWI=,iv:AMPwUd2SYWCbR9NYg5alM5z0kNhO8wZ6CaN5jrboEMA=,tag:U2mOdU14dk0c/XPTa/OVlw==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNUpnUzk5MkVsSUFWaEJ3
        TjJra1I4TkpEemdzTnJvTGpuV204SERSbG1VCjZjK0IzSUprQzlqaXlnVmROYXVD
        UW9ZMGdlSWNTdVh3V1BoNlgycjRoMkEKLS0tIEtCODZjNkhvOS85UWxlMks0dHNz
        ZGpSMlVvTHIyZDlPSjMyTEpXSmJSZ1kKk4jsgB9PxQXqbVNUPjyrP233IGwQhP9c
        YB78A4TofcaL0NV21vDZdHQF3QKuWay5XySv8MoCM84JxNMwfcUG/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T02:46:48Z"
  mac: ENC[AES256_GCM,data:HWmJUlKsCN+qbSz4sNjmdlWmri3QLy+n27L0wfrXHa4WbO077iD7ejcqBRNTKLRSL6OjaSxGmfQ7jsK5k067xWeS8P7aTio9MrNNNtSt35XQQfmDEaS42befXNuj7vnPQSCQXsld40LFGa03T09X9Y+rw/E6amKSdTQhiBOcEbE=,iv:z5M0Cl/cUJJVLQQbBugxxBQaOjtReblo6TARbyzzuXM=,tag:S94FEIaH7hoU1D7otW+v5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
