apiVersion: v1
kind: Secret
metadata:
  name: wakapi-oidc
  namespace: wakapi
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:i6KNmMFmABD/+Uc4mOppRio9YQ1zxWCfo77ili37szchwNvQSGQG+Q==,iv:4JflIz5R8wetsHKN+2hOFTJMz7WNAPNIvyWwRSgFAq8=,tag:RD0N66kiafmkJNf2chPmVA==,type:str]
  client-secret: ENC[AES256_GCM,data:AX8eF1722FnfLd8UxCjmkjiBJET1KdXJPZGFiGx7RSfGZAeHqHhNkld5zEj0pEq5uta85emw8/XBsHZDuaH65O3vWYBGLG3/rCBS4eUhb85OZLsGx4H4GD22lriDF13wHbBAmdiww3SjpDxUhMwLmlb4nKqip1KFFlF2u7rGEpc=,iv:fH6EUjtw2Lybd/ENV4I779VnCZoYuGOGCAzndbmswf8=,tag:W7C8hveHzV0+POgHv0fnqg==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVjdIcUtYUG9ZNDJkSzNW
        c3hvSk9ZOWlLSzNtbytyd0Z0RCtXVExxR1FrCk95a0RHa3dUMHR2RExieFY5Zk5L
        OXR5c3F0djd5bHF4UnhhaDREY25UNVUKLS0tIE02RDBiUU5MRHVqNEFHQnVFUUtD
        dmV6aXJFSU5HVitXb0FqTkxnVldoS0EKzq96KnPQ6vPaQH1nnFpZVHgxKyKCQzww
        OBV7dLGnRyiRdQJNrz+63S85pBfrw1i+CSD1fWAGSg6uy4D0PhDLtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T03:32:27Z"
  mac: ENC[AES256_GCM,data:Gn4Gm620AvupwGnIKKMg5LovdaExkK8UH6goXeNTPD5wp3j3mOfzoYpnl9+2j9wjsumtiqIyorCLQLCDd/64Tf/MlvFlww45VF2XEUljTekfhiwoIYkbMIU5DF2OlLqdLw1Xwv0VQ5JI7lHnUj8/d7ZgWfb49aMHQReeyesgcpU=,iv:06RD35tEk5xbhgta4Pum6LO9OBJWwjmIDGe4E76MAw8=,tag:01pwPOR3TD0/UxoX7xiYUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
