apiVersion: v1
kind: Secret
metadata:
  name: hubble-ui-oidc-secret
  namespace: kube-system
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:4m9uGfK80r2rgnU7il8afzyuRoSZNGEWDMcCRgZRBittGWESOtucJAPxqK11U47ZSxQagSkSC9BAb0PnXeQieg4nBuHLl5FE2LMAgE/DdzA=,iv:9nUiur8Vd10qx+L1LmU6IMjo0Q9djEo+5HYgT0RyJZM=,tag:rMUec0HeyZDNcRnJRWzRng==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcktjbEM3bWdQOWZxUnJ6
        RjBTbXdhRUt5UWdlNXVVUjFFd3V2ZTJhS1drCkR0U0dvVTJFWDFsaXdFYThBT0tq
        TkYweXB3aXJjRk9hVzZpK080VkU3NU0KLS0tIFdrVk4wZi9tTFdTS0wvdW1pRGZl
        YmtLZWtkTDMveGJ6aEVPbCs0MG1GTTAKLLCytbimdULxFFAXoHfA+LlQE4/I+uTU
        9FOs28A1xopJv0qw7cNV2a3zMlCCH3MMnJs5cqOoIB9+FK55Rg8AVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-25T19:13:02Z"
  mac: ENC[AES256_GCM,data:53n99Fh2uh95F9D8JrrNxcsRs8V65F01jRGMjdSnlVSWb7N+1Brv4QhWiFTMVzGBa/NirDgPSy4Ax1+sZlLeGeyGMsYUfXFNiL1veuT2c1/6kmCDdWNtJxzKA0XXiczzDZypXtp3PJdVbViVjVPrIkJ1XGK+3pP4xac5Cw+vhlA=,iv:mHeelUMWcUeCTsLHyO9fybSJjHVMz4wiEAaiV1tF5l4=,tag:iTPydebEB1HWWoN88eskwQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
