apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: observability-system
spec:
  interval: 1h
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.72.5
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
  install:
    createNamespace: true
  values:
    grafana:
      enabled: false
    defaultDashboards:
      enabled: false
    vmsingle:
      enabled: true
      spec:
        retentionPeriod: "180d"
        storage:
          storageClassName: cluster-nvmf
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 150Gi
    vmagent:
      enabled: true
      spec:
        scrapeInterval: 15s
        selectAllByDefault: true
        extraArgs:
          promscrape.streamParse: "true"
    vmalert:
      enabled: true
      spec:
        evaluationInterval: 30s
        selectAllByDefault: true
        extraArgs:
          external.url: https://grafana.tale.me
          external.alert.source: 'explore?orgId=1&left={"datasource":"VictoriaMetrics","queries":[{"expr":{{ "{{" }}.Expr|jsonEscape|queryEscape{{ "}}" }},"refId":"A"}],"range":{"from":"{{ "{{" }} .ActiveAt.UnixMilli {{ "}}" }}","to":"now"}}'
    alertmanager:
      enabled: true
      spec:
        externalURL: https://grafana.tale.me
        configSecret: ""
        secrets:
          - pushover-credentials
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: cluster-nvmf
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
      config:
        route:
          receiver: pushover
          group_by: ["alertname", "namespace"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
          routes:
            - receiver: blackhole
              matchers:
                - alertname =~ "InfoInhibitor|Watchdog"
            - receiver: pushover
              matchers:
                - severity =~ "critical|warning"
        receivers:
          - name: blackhole
          - name: pushover
            pushover_configs:
              - user_key_file: /etc/vm/secrets/pushover-credentials/user_key
                token_file: /etc/vm/secrets/pushover-credentials/api_token
                priority: '{{ if eq .CommonLabels.severity "critical" }}1{{ else }}0{{ end }}'
                title: "{{ .CommonLabels.alertname }}"
                message: '{{ range .Alerts }}{{ .Annotations.summary }}{{ if .Annotations.description }}{{ "\n" }}{{ .Annotations.description }}{{ end }}{{ "\n" }}{{ end }}'
                url: "{{ (index .Alerts 0).GeneratorURL }}"
    defaultRules:
      enabled: true
      groups:
        general:
          create: false
      rules:
        KubeJobFailed:
          enabled: false
        LogErrors:
          enabled: false
        CPUThrottlingHigh:
          spec:
            expr: >-
              sum(increase(container_cpu_cfs_throttled_periods_total{container!="",
              }[5m])) by (cluster, container, pod, namespace) /
              sum(increase(container_cpu_cfs_periods_total{}[5m])) by (cluster,
              container, pod, namespace) > ( 50 / 100 )
            for: 30m
    victoria-metrics-operator:
      crds:
        enabled: false
        plain: false
      operator:
        disable_prometheus_converter: true
    prometheus-node-exporter:
      enabled: true
    kube-state-metrics:
      enabled: true
    kubeProxy:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeApiServer:
      enabled: true
    kubelet:
      enabled: true
    coreDns:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logs-collector
  namespace: observability-system
spec:
  dependsOn:
    - name: victoria-metrics-k8s-stack
  interval: 1h
  chart:
    spec:
      chart: victoria-logs-collector
      version: 0.2.14
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
  values:
    remoteWrite:
      - url: http://vlsingle-vlogs.observability-system.svc.cluster.local:9428
