apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - manifests/namespace.yaml
  - manifests/grafana-oidc.sops.yaml
  - manifests/grafana-http-route.yaml
  - manifests/pushover-secret.sops.yaml
  - manifests/grafana-db-credentials.sops.yaml
  - manifests/vmbackup-credentials.sops.yaml
  - manifests/grafana.yaml
  - manifests/grafana-datasources.yaml
  - manifests/grafana-dashboards.yaml
  - manifests/vmrules.yaml
