apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - manifests/grafana-oidc.sops.yaml
  - manifests/grafana-renderer-token.sops.yaml
  - manifests/grafana-http-route.yaml
  - manifests/pushover-secret.sops.yaml
  - manifests/grafana-db-credentials.sops.yaml
  - manifests/vmagent-rbac.yaml
  - manifests/vlogs.yaml
  - manifests/grafana.yaml
  - manifests/grafana-renderer.yaml
  - manifests/grafana-live-image.yaml
  - manifests/grafana-datasources.yaml
  - manifests/grafana-overview.yaml
  - manifests/grafana-public.yaml
  - manifests/grafana-kubernetes.yaml
  - manifests/grafana-network.yaml
  - manifests/grafana-storage.yaml
  - manifests/grafana-postgres.yaml
  - manifests/grafana-monitoring.yaml
  - manifests/nut-scrape.yaml
  - manifests/flux-scrape.yaml
  - manifests/blackbox.yaml
  - manifests/vmrules.yaml
