apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - manifests/grafana-oidc.sops.yaml
  - manifests/grafana-renderer-token.sops.yaml
  - manifests/grafana-http-route.yaml
  - manifests/pushover-secret.sops.yaml
  - manifests/grafana-db-credentials.sops.yaml
  - manifests/vmagent-rbac.yaml
  - manifests/vlogs.yaml
  - manifests/grafana.yaml
  - manifests/grafana-renderer.yaml
  - manifests/grafana-live-image.yaml
  - manifests/grafana-datasources.yaml
  - manifests/grafana-overview.yaml
  - manifests/grafana-public.yaml
  - manifests/grafana-kubernetes.yaml
  - manifests/grafana-network.yaml
  - manifests/grafana-storage.yaml
  - manifests/grafana-postgres.yaml
  - manifests/grafana-monitoring.yaml
  - manifests/nut-scrape.yaml
  - manifests/flux-scrape.yaml
  - manifests/blackbox.yaml
  - manifests/vmrules.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-dashboard-overview
    namespace: observability-system
    files:
      - dashboards/overview.json
  - name: grafana-dashboard-public
    namespace: observability-system
    files:
      - dashboards/public.json
  - name: grafana-dashboard-kubernetes
    namespace: observability-system
    files:
      - dashboards/kubernetes.json
  - name: grafana-dashboard-network
    namespace: observability-system
    files:
      - dashboards/network.json
  - name: grafana-dashboard-storage
    namespace: observability-system
    files:
      - dashboards/storage.json
  - name: grafana-dashboard-postgres
    namespace: observability-system
    files:
      - dashboards/postgres.json
  - name: grafana-dashboard-monitoring
    namespace: observability-system
    files:
      - dashboards/monitoring.json
