alertmanager:
  enabled: false
grafana:
  enabled: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: "cluster-nvmf"
    accessModes:
      - ReadWriteOnce
    size: 25Gi
  grafana.ini:
    server:
      root_url: "https://grafana.tale.me"
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      auto_login: false
      name: Pocket ID
      client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
      client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
      scopes: "openid email profile"
      auth_url: https://idp.tale.me/authorize
      token_url: https://idp.tale.me/api/oidc/token
      email_attribute_path: email
      login_attribute_path: preferred_username
      skip_org_role_sync: true
  extraSecretMounts:
    - name: grafana-oidc
      secretName: grafana-oidc
      defaultMode: 0440
      mountPath: /etc/secrets/auth_generic_oauth
      readOnly: true
kubeProxy:
  enabled: false
prometheus:
  enabled: true
  prometheusSpec:
    retention: 24h # We have VictoriaMetrics for long-term storage
    retentionSize: 20GB
    scrapeInterval: 15s
    scrapeTimeout: 10s
    evaluationInterval: 30s
    remoteWrite:
      - url: http://victoriametrics-victoria-metrics-single-server.observability-system.svc.cluster.local:8428/api/v1/write
        name: victoriametrics
        remoteTimeout: 30s
        sendExemplars: true
        queueConfig:
          capacity: 20000
          maxShards: 8
          minShards: 1
          maxSamplesPerSend: 2000
          batchSendDeadline: 5s
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "cluster-nvmf"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 25Gi
