apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted-data
  namespace: home-automation
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: cluster-nvmf
  resources:
    requests:
      storage: 5Gi
