apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  sourcePVC: home-assistant-data
  trigger:
    schedule: "15 3 * * *"
  restic:
    repository: home-assistant-restic
    cacheCapacity: 2Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: eufy-security-ws
  namespace: home-automation
spec:
  sourcePVC: eufy-ws-data
  trigger:
    schedule: "30 3 * * *"
  restic:
    repository: eufy-security-ws-restic
    cacheCapacity: 1Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: scrypted
  namespace: home-automation
spec:
  sourcePVC: scrypted-data
  trigger:
    schedule: "45 3 * * *"
  restic:
    repository: scrypted-restic
    cacheCapacity: 1Gi
