apiVersion: v1
kind: Secret
metadata:
  name: qui-db-credentials
  namespace: qui
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:Msg5lcFOxpC4Z3BOP5BkiplAAfvXDWkg9gTKpOcwDbI0TLgvrB4zCkPmZ5HhdsR/Y0cgLOg1/YvEl4EejCRwjQ==,iv:faHP3WmSGBJNRlDVXxSppcvW8tvrrkNxdA/CjNdAPQg=,tag:cM6hmvsQZL3UdziHywEIcQ==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VHp2Y2c2RWpIRUVGYU1k
        MkVUUHVKVkFKTUR3eG4wcUhnai9aamFIZ1ZNCnJQcEtQMmxxY21sQ2VFUmowVnJ0
        MXpMR3VIYUZQbkFUdWMzWVpQcjA5MUUKLS0tIDZ2aWJZUTNFWHo5NDkyZnZ4ZWlP
        Uy9IR2NDZkFDWWhQRFovdXEyVHZTNk0KfrWkcb+uiFswfrmKVBOUh/tGZ2hqjZiu
        6bHODt4dWFoQqmSCEzU9niP/ZnSAXcWax9x+hAA6ndHkPD6RFmnJuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-03T21:22:13Z"
  mac: ENC[AES256_GCM,data:uCZakJmApdM9DHLl91ranQTNZ6kMiWbt0yQsxLAprUwPsgIiRrmxzrYbIbZO8KDNVsZ91cJZDy3Kq3YDdcj/sXqATphNdTGcl+r2ezZHwrW9/+50v0ZGhFDmR5ebtfQ2D2JWKa1lG3Lo806UxI7qY50tHJOfTMl5Uo0xFp+GbDE=,iv:NlFbdJajRydkQ0IT3X1C9gqCyJQtuolZWZMw6qfoKpo=,tag:US6X94iCLW54byPC1i1Mbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
