apiVersion: v1
kind: Secret
metadata:
  name: qui-oidc
  namespace: autobrr
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:5jzTRaevC3cSMOGVTEwDY3obqYdI83I+2n3fqKXn4yTcupI3H6KyFg==,iv:9RV1WF/rZjfJ+a/kcWgs7cdnA1lY0ZQcrRTgZx/btjI=,tag:EAqTaviJntvYz7X6dOSTfw==,type:str]
  client-secret: ENC[AES256_GCM,data:Nr5z34dVDCqqD+V7Bz5Hc0YLjdRXlrd8TX36in7AP0c1ytwgun6ySnbIGZUljdnNpja4BAVvlB/xPWtYeiGB5o6witb0AS4HX1FaHb6yWlY0hQtZzBk=,iv:DsBpejDyD39eeXX+BFtCGKXQtNArRQu6wqRjAMwzADA=,tag:UHuw7FH1mnWD/1rwnA3PGw==,type:str]
sops:
  age:
    - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SDY4NGlXb2pTM3VDcG9F
        bisrK2Z2R01qbTVPQm43L1FkcXhLNVRPV1FvCjVVbkVYcTRVTWQyVHRyZnI4YlFI
        RnBGL05EdWNRdVFtcys4SERJaXpLREUKLS0tIHZDaTMvZldoWFNpNGs5aTkvMncx
        SUNLdSszWmtheDcvSE5pV0RLajk3ZzAKfMcxVxaaUv3mCE3hafjXwZDgjaiCqtHh
        Lcwibmm+DBSuCh6ak1nnTg+o5Ho4kzXA1uBQTWLKQGZMaPvx3FkHTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-03T21:46:11Z"
  mac: ENC[AES256_GCM,data:2/JrFAhbhiTwBpwQMysBzfgpFGYv9kaSiw/4SVcov9sqlBcSeNGTZk+2fI33eaceUsH3zkZFtzGm2iwWQJqj3QYFIQVbFIP6WceRnNnjjjBs6hvzGcY/koKZkXgbl9BiAzgwOWlB7W2ngYJTH/bZ4oBVHGwn/FfCNy+xSqWQHb8=,iv:AexUqdmDjhkxp/Syx/GUnFDFpbNePX5tq72vcX2wFr4=,tag:H5z42u1PlxKFtGJ5o8DWvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
